### PR TITLE
Kink/Fix and Update Kink Scraper

### LINKED ISSUE #1870: Kink network, not working
Hello, since a few weeks there are no matches from kink.com.
I spent a lot of time to find a solution.
Nothing work.. New library.. Restart Plex.. and so on.
I found an ERROR entry in the Log file "com.plexapp.agents.phoenixadult"

As result of every scan i have done the error is nearly the same. "... index error... <lambda>.."

```
2024-01-05 15:48:45,785 (7f0a710afb38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgphOGZkOTZjMWUzNmY5ZTliczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczUyClRIRVVQUEVSRkxPT1IgNzkwNyBTYXJhaCBTaGV2b24sIEJlbGxhIFJvc3NpIFRyYWlsZXJzNApuYW1lczE5MwolMkZzaGFyZSUyRkNBQ0hFREVWMl9EQVRBJTJGa2luayUyRlRVRiUyRjIwMDklMkZUSEVVUFBFUkZMT09SJTIwLSUyMDc5MDclMjBfJTIwU2FyYWglMjBTaGV2b24lMkMlMjBCZWxsYSUyMFJvc3NpJTJGVEhFVVBQRVJGTE9PUiUyMC0lMjA3OTA3JTIwXyUyMFNhcmFoJTIwU2hldm9uJTJDJTIwQmVsbGElMjBSb3NzaV90cmFpbGVyJTJFbXA0czgKZmlsZW5hbWVzNDAKNTU1YjQzNjQzNmNiYjhmMTgzNWEyYjcyMTlmNzMyYjQ4MmY2NDI5Y3M4CnBsZXhIYXNoczUKMzg5NzJzOApkdXJhdGlvbnM2CjE2Nzk3OHMyCmlkcjAK
2024-01-05 15:48:45,787 (7f0a710afb38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2024-01-05 15:48:45,790 (7f0a710afb38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgphOGZkOTZjMWUzNmY5ZTliczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczUyClRIRVVQUEVSRkxPT1IgNzkwNyBTYXJhaCBTaGV2b24sIEJlbGxhIFJvc3NpIFRyYWlsZXJzNApuYW1lczE5MwolMkZzaGFyZSUyRkNBQ0hFREVWMl9EQVRBJTJGa2luayUyRlRVRiUyRjIwMDklMkZUSEVVUFBFUkZMT09SJTIwLSUyMDc5MDclMjBfJTIwU2FyYWglMjBTaGV2b24lMkMlMjBCZWxsYSUyMFJvc3NpJTJGVEhFVVBQRVJGTE9PUiUyMC0lMjA3OTA3JTIwXyUyMFNhcmFoJTIwU2hldm9uJTJDJTIwQmVsbGElMjBSb3NzaV90cmFpbGVyJTJFbXA0czgKZmlsZW5hbWVzNDAKNTU1YjQzNjQzNmNiYjhmMTgzNWEyYjcyMTlmNzMyYjQ4MmY2NDI5Y3M4CnBsZXhIYXNoczUKMzg5NzJzOApkdXJhdGlvbnM2CjE2Nzk3OHMyCmlkcjAK
2024-01-05 15:48:45,791 (7f0a710afb38) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': 'a8fd96c1e36f9e9b', 'name': 'THEUPPERFLOOR 7907 Sarah Shevon, Bella Rossi Trailer', 'filename': '%2Fshare%2FCACHEDEV2_DATA%2Fkink%2FTUF%2F2009%2FTHEUPPERFLOOR%20-%207907%20_%20Sarah%20Shevon%2C%20Bella%20Rossi%2FTHEUPPERFLOOR%20-%207907%20_%20Sarah%20Shevon%2C%20Bella%20Rossi_trailer%2Emp4', 'plexHash': '555b436436cbb8f1835a2b7219f732b482f6429c', 'duration': '38972', 'id': '167978'}
2024-01-05 15:48:45,793 (7f0a710afb38) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/library/metadata/167978/tree'
2024-01-05 15:48:45,811 (7f0a710afb38) :  INFO (__init__:68) - ***MEDIA TITLE [from media.name]*** THEUPPERFLOOR 7907 Sarah Shevon, Bella Rossi Trailer
2024-01-05 15:48:45,811 (7f0a710afb38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: THEUPPERFLOOR 7907 Sarah Shevon, Bella Rossi Trailer
2024-01-05 15:48:45,856 (7f0a710afb38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: THEUPPERFLOOR 7907 Sarah Shevon, Bella Rossi Trailer
2024-01-05 15:48:45,894 (7f0a710afb38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 502
2024-01-05 15:48:45,894 (7f0a710afb38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2024-01-05 15:48:45,909 (7f0a710afb38) :  INFO (PAsearchSites:96) - Search Title (before date processing): 7907 Sarah Shevon, Bella Rossi Trailer
2024-01-05 15:48:45,911 (7f0a710afb38) :  INFO (__init__:70) - {'siteName': 'theupperfloor', 'searchDate': None, 'siteNum': 502, 'searchTitle': '7907 Sarah Shevon, Bella Rossi Trailer'}
2024-01-05 15:48:45,914 (7f0a710afb38) :  INFO (PAsearchData:23) - SearchData.title: 7907 Sarah Shevon, Bella Rossi Trailer
2024-01-05 15:48:45,915 (7f0a710afb38) :  INFO (PAsearchData:29) - SearchData.filename: THEUPPERFLOOR - 7907
2024-01-05 15:48:45,916 (7f0a710afb38) :  INFO (__init__:107) - Provider: networkKink
2024-01-05 15:48:45,920 (7f0a710afb38) :  INFO (PAutils:183) - Requesting GET "http://www.kink.com/shoot/7907"
2024-01-05 15:48:47,252 (7f0a710afb38) :  INFO (PAutils:282) - GZip request saved as "bc98d4f705ef4f4c8afd54d3b7d473a4.gz"
2024-01-05 15:48:47,294 (7f0a710afb38) :  ERROR (__init__:111) - Traceback (most recent call last):
  File "/share/CACHEDEV3_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 109, in search
    provider.search(results, lang, siteNum, search)
  File "/share/CACHEDEV3_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkKink.py", line 33, in search
    score = 100 - Util.LevenshteinDistance(searchData.date, releaseDate)
  File "/share/CACHEDEV3_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-fb6452ebf/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2024-01-05 15:48:47,300 (7f0a710afb38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2024-01-05 15:48:47,301 (7f0a710afb38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
```

I have around 1000 videos from kink i want to integrate in PLEX.
Newest PLEX version is running on QNAP TS-453 NAS.

Thanks for your support.

BR,
Andy

### PR DESCRIPTION
**Pull request by diamondpete**
Fixes #1870

### CODE REVIEW

**Comment by andy-online842** [comment]
Hi @diamondpete,
thanks for your support.
But unfortunately it does not work.
The same entry in the log file is occuring.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/13852674/com.plexapp.agents.phoenixadult.log)
I have attached the log file.
"...IndexError: list index out of range..."
I have created a new plain library but adding my kink media and the assignment with PAhelper didn't work.
Thank you.
BR,
Andy

**Comment by diamondpete** [comment]
> The same entry in the log is occurring [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/13852674/com.plexapp.agents.phoenixadult.log)
> 
> I have attached the log file.
> 
> "...IndexError: list index out of range..."
> 

@andy-online842 

Your Plex instance is not referencing the new code. This hasn't been merged yet, so please make sure you have updated all the files. I am not familiar with Plex on QNAP, but you may need to restart the device for it to use the updated code.

**Comment by Faerch** [comment]
Is it possible to match with Scene ID?
If so can you give an example?

I can only get it to match witch Actor or Title.

**Comment by diamondpete** [comment]
@Faerch fixed in #1875

**Pull request merged**
