### PR TITLE
Update PAsiteList.py

### PR DESCRIPTION
**Pull request by drraymond27**

### CODE REVIEW

**Comment by DirtyRacer1337** [comment]
one pr

**Comment by drraymond27** [comment]
@DirtyRacer1337 sorry, I tried but I don't know how do that. When I click in open pr, automatically the page create a new PR,, don't give me a choice to use the same PR.
I need instructions. 😞

**Comment by DirtyRacer1337** [comment]
Use this, not website https://desktop.github.com/

**Comment by drraymond27** [comment]
@DirtyRacer1337 thanks

**Pull request closed without merging**
