### PR TITLE
Update networkMetArt.py

### PR DESCRIPTION
**Pull request by b0nensfw**
Fix MetArtNetwork #243

### CODE REVIEW

**Comment by claygoldfinch** [comment]
Just tested with MetArt, SexArt, and VivThomas - all working! Nice job @b0nensfw.

Still running into some issues with MetArtX scenes:
```
2019-09-15 16:56:32,148 (3e10) :  INFO (logkit:16) - *******MEDIA TITLE****** Metartx 17 11 25 Alexa Grace Unleashed
2019-09-15 16:56:32,148 (3e10) :  INFO (logkit:16) - Getting Search Settings for: Metartx 17 11 25 Alexa Grace Unleashed
2019-09-15 16:56:32,148 (3e10) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation: Metartx 17 11 25 Alexa Grace Unleashed
2019-09-15 16:56:32,153 (3e10) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Metartx 17 11 25 Alexa Grace Unleashed
2019-09-15 16:56:32,154 (3e10) :  INFO (logkit:16) - ^^^^^^^ siteID: 754
2019-09-15 16:56:32,154 (3e10) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2019-09-15 16:56:32,155 (3e10) :  INFO (logkit:16) - metartx vs metartx
2019-09-15 16:56:32,155 (3e10) :  INFO (logkit:16) - 1
2019-09-15 16:56:32,155 (3e10) :  INFO (logkit:16) - 7
2019-09-15 16:56:32,155 (3e10) :  INFO (logkit:16) - searchTitle (before date processing): 17 11 25 Alexa Grace Unleashed
2019-09-15 16:56:32,155 (3e10) :  INFO (logkit:16) - Search Title: Alexa Grace Unleashed
2019-09-15 16:56:32,155 (3e10) :  INFO (logkit:16) - Search Date: 2017-11-25
2019-09-15 16:56:32,155 (3e10) :  INFO (logkit:16) - Alexa%20Grace%20Unleashed
2019-09-15 16:56:32,157 (3e10) :  INFO (logkit:16) - url: https://www.metartx.com/search/Alexa%20Grace%20Unleashed/relevance~0~68~-~-~-~-~-~-/1
2019-09-15 16:56:32,160 (3e10) :  DEBUG (networking:166) - Requesting 'https://www.metartx.com/search/Alexa%20Grace%20Unleashed/relevance~0~68~-~-~-~-~-~-/1'
2019-09-15 16:56:33,381 (3e10) :  INFO (logkit:16) - resultsNum: 11
2019-09-15 16:56:33,381 (3e10) :  INFO (logkit:16) - >>>VALID RESULT<<<
2019-09-15 16:56:33,381 (3e10) :  INFO (logkit:16) - Result title: Unleashed
2019-09-15 16:56:33,381 (3e10) :  INFO (logkit:16) - curID: +model+alexa-grace+movie+20171125+UNLEASHED
2019-09-15 16:56:33,381 (3e10) :  INFO (logkit:16) - releaseDate: Nov 24, 2017
2019-09-15 16:56:33,382 (3e10) :  INFO (logkit:16) - Score: 90
2019-09-15 16:56:33,382 (3e10) :  INFO (logkit:16) - >>>VALID RESULT<<<
2019-09-15 16:56:33,382 (3e10) :  INFO (logkit:16) - Result title: Orange Crush
2019-09-15 16:56:33,382 (3e10) :  INFO (logkit:16) - curID: +model+alexa-grace+movie+20171223+ORANGE_CRUSH
2019-09-15 16:56:33,382 (3e10) :  INFO (logkit:16) - releaseDate: Dec 22, 2017
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - Score: 90
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - >>>VALID RESULT<<<
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - Result title: Under Lock
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - curID: +model+alexa-grace+movie+20180120+UNDER_LOCK
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - releaseDate: Jan 19, 2018
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - Score: 91
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - >>>VALID RESULT<<<
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - Result title: Wild Soul
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - curID: +model+alexa-grace+movie+20171031+WILD_SOUL
2019-09-15 16:56:33,384 (3e10) :  INFO (logkit:16) - releaseDate: Oct 30, 2017
2019-09-15 16:56:33,385 (3e10) :  INFO (logkit:16) - Score: 90
2019-09-15 16:56:33,385 (3e10) :  INFO (logkit:16) - >>>VALID RESULT<<<
2019-09-15 16:56:33,385 (3e10) :  INFO (logkit:16) - Result title: Cuts
2019-09-15 16:56:33,385 (3e10) :  INFO (logkit:16) - curID: +model+lucy-li+movie+20170823+CUTS
2019-09-15 16:56:33,385 (3e10) :  INFO (logkit:16) - releaseDate: Aug 22, 2017
2019-09-15 16:56:33,387 (3e10) :  INFO (logkit:16) - Score: 90
2019-09-15 16:56:33,387 (3e10) :  INFO (logkit:16) - >>>VALID RESULT<<<
2019-09-15 16:56:33,387 (3e10) :  INFO (logkit:16) - Result title: Dancing On The Bridge 2
2019-09-15 16:56:33,387 (3e10) :  INFO (logkit:16) - curID: +model+kitri+movie+20180910+DANCING_ON_THE_BRIDGE_2
2019-09-15 16:56:33,387 (3e10) :  INFO (logkit:16) - releaseDate: Sep 09, 2018
2019-09-15 16:56:33,388 (3e10) :  INFO (logkit:16) - Score: 90
2019-09-15 16:56:33,388 (3e10) :  INFO (logkit:16) - url: https://www.metartx.com/search/Alexa%20Grace%20Unleashed/relevance~0~68~-~-~-~-~-~-/2
2019-09-15 16:56:33,390 (3e10) :  DEBUG (networking:166) - Requesting 'https://www.metartx.com/search/Alexa%20Grace%20Unleashed/relevance~0~68~-~-~-~-~-~-/2'
2019-09-15 16:56:33,872 (3e10) :  INFO (logkit:16) - resultsNum: 0
2019-09-15 16:56:33,875 (3e10) :  DEBUG (runtime:88) - Sending packed state data (3188 bytes)
2019-09-15 16:56:33,875 (3e10) :  DEBUG (runtime:924) - Response: [200] str, 2696 bytes
2019-09-15 16:56:35,667 (2d1c) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzMgo5NXM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXM4OQpjb20ucGxleGFwcC5hZ2VudHMucGhvZW5peGFkdWx0Oi8vK21vZGVsK2FsZXhhLWdyYWNlK21vdmllKzIwMTcxMTI1K1VOTEVBU0hFRHw3NTQ%40bGFuZz1lbnM0Cmd1aWRzNDcKK21vZGVsK2FsZXhhLWdyYWNlK21vdmllKzIwMTcxMTI1K1VOTEVBU0hFRHw3NTRzMgppZHIwCg__
2019-09-15 16:56:35,667 (2d1c) :  DEBUG (runtime:49) - Received packed state data (1840 bytes)
2019-09-15 16:56:35,668 (2d1c) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzMgo5NXM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXM4OQpjb20ucGxleGFwcC5hZ2VudHMucGhvZW5peGFkdWx0Oi8vK21vZGVsK2FsZXhhLWdyYWNlK21vdmllKzIwMTcxMTI1K1VOTEVBU0hFRHw3NTQ@bGFuZz1lbnM0Cmd1aWRzNDcKK21vZGVsK2FsZXhhLWdyYWNlK21vdmllKzIwMTcxMTI1K1VOTEVBU0hFRHw3NTRzMgppZHIwCg__
2019-09-15 16:56:35,670 (2d1c) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.phoenixadult://+model+alexa-grace+movie+20171125+UNLEASHED|754?lang=en
2019-09-15 16:56:35,671 (2d1c) :  DEBUG (model:234) - Deserializing from C:\Users\Phoenix\AppData\Local\Plex Media Server\Metadata\Movies\6\589ef766e3e0fec01eb410ddc221df86c15175a.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2019-09-15 16:56:35,671 (2d1c) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/95/tree'
2019-09-15 16:56:35,678 (2d1c) :  INFO (logkit:16) - ******UPDATE CALLED*******
2019-09-15 16:56:35,678 (2d1c) :  INFO (logkit:16) - 754
2019-09-15 16:56:35,680 (2d1c) :  DEBUG (networking:166) - Requesting '/model/alexa-grace/movie/20171125/UNLEASHED'
2019-09-15 16:56:35,681 (2d1c) :  CRITICAL (core:574) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://+model+alexa-grace+movie+20171125+UNLEASHED|754?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-22929c8a2\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\Phoenix\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 1735, in update
    metadata = PAsearchSites.networkMetArt.updateMetArt(metadata,siteID,movieGenres,movieActors)
  File "C:\Users\Phoenix\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkMetArt.py", line 146, in updateMetArt
    detailsPageElements = HTML.ElementFromURL(url)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-22929c8a2\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\parsekit.py", line 482, in ElementFromURL
    method=method,
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-22929c8a2\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-22929c8a2\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-22929c8a2\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 141, in __init__
    self.load()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-22929c8a2\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 421, in open
    protocol = req.get_type()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /model/alexa-grace/movie/20171125/UNLEASHED

2019-09-15 16:56:35,681 (2d1c) :  DEBUG (model:229) - Serializing to C:\Users\Phoenix\AppData\Local\Plex Media Server\Metadata\Movies\6\589ef766e3e0fec01eb410ddc221df86c15175a.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2019-09-15 16:56:35,684 (2d1c) :  DEBUG (runtime:88) - Sending packed state data (1872 bytes)
2019-09-15 16:56:35,684 (2d1c) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by b0nensfw** [comment]
I did not have time to check other MetArt website (I was fixing it for myself for a SexArt video). If I have time I will check on this error, but it will not be before this weekend

**Comment by b0nensfw** [comment]
@claygoldfinch could you update the issue with the info you just provided (someone else maybe will have the time before me)

**Comment by claygoldfinch** [comment]
Absolutely - Issue updated. Going to merge this PR in the meantime.

**Pull request merged**
