### PR TITLE
add Clubseventeen

### PR DESCRIPTION
**Pull request by ferengi82**

### CODE REVIEW

**Comment by claygoldfinch** [comment]
This doesn't seem to be working for me. Here's my log:

```
2019-08-10 17:43:51,963 (5a90) :  INFO (logkit:16) - *******MEDIA TITLE****** Clubseventeen Eva Elfie
2019-08-10 17:43:51,963 (5a90) :  INFO (logkit:16) - Getting Search Settings for: Clubseventeen Eva Elfie
2019-08-10 17:43:51,963 (5a90) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation: Clubseventeen Eva Elfie
2019-08-10 17:43:51,969 (5a90) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Clubseventeen Eva Elfie
2019-08-10 17:43:51,970 (5a90) :  INFO (logkit:16) - ^^^^^^^ siteID: 764
2019-08-10 17:43:51,970 (5a90) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2019-08-10 17:43:51,970 (5a90) :  INFO (logkit:16) - clubseventeen vs clubseventeen
2019-08-10 17:43:51,970 (5a90) :  INFO (logkit:16) - 1
2019-08-10 17:43:51,970 (5a90) :  INFO (logkit:16) - 7
2019-08-10 17:43:51,970 (5a90) :  INFO (logkit:16) - searchTitle (before date processing): Eva Elfie
2019-08-10 17:43:51,970 (5a90) :  INFO (logkit:16) - Search Title: Eva Elfie
2019-08-10 17:43:51,970 (5a90) :  INFO (logkit:16) - Eva%20Elfie
2019-08-10 17:43:51,974 (5a90) :  DEBUG (networking:166) - Requesting 'https://www.clubseventeen.com/girl.php?slug=Eva_Elfie'
2019-08-10 17:43:53,122 (5a90) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2019-08-10 17:43:53,122 (5a90) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
```

https://www.clubseventeen.com/girl.php?slug=Eva_Elfie redirects to https://www.clubseventeen.com/clubmodels.php on my setup.

**Comment by ferengi82** [comment]
not good ... https://www.clubseventeen.com/girl.php?slug=tiny_teen works, but is obviously not the right name.

1. use a list for girls with a different url (like in PAactors)? => only rational if there only a few.
2. google for it, if site redirected to clubmodels (https://www.google.com/search?q=https%3A%2F%2Fwww.clubseventeen.com%2Fgirl.php%3Fslug%3D+eva+elfie) seems to work not  too bad.

any other suggestions? if not i think im trying 2.

**Comment by claygoldfinch** [comment]
To be honest, I think DirectURL might be the best (and most reliable) way to go. Just going through the list of actresses (found [here](https://www.clubseventeen.com/discount/idealgasm/girls.php)) it appears as though there are quite a few that would make searching via actress difficult. Plus the scene URLs seem intuitive enough that it'd be relatively easy to name your files to ensure good matches - most scenes should work without altering the name of the scene much.

**Easy example:** 
Scene: 
https://www.clubseventeen.com/video.php?slug=little_caprice_hot_bathtub_show
Filename:
ClubSeventeen - Little Caprice Bathtub Show

**Harder example:**
Scene:
https://www.clubseventeen.com/video.php?slug=live_webcam_recording_little_caprice_1532498837
Filename:
ClubSeventeen - Live webcam recording Little Caprice 1532498837

Unfortunately you'd probably have to significantly change PAactors whichever way you go.

**Comment by ferengi82** [comment]
ok, i think about it and make a new pull request later

**Pull request closed without merging**
