### PR TITLE
Post Processing Improvements

### PR DESCRIPTION
**Pull request by SgtBatten**

### CODE REVIEW

**Comment by SgtBatten** [comment]
Well tickle me Pink everyone. I've managed to get this script to a point where it can batch rename files pretty damn well.

Of course the original functionality of automating rename after a new file is downloaded is still working and its better than ever.

I will need to get some feedback from everyone on what your existing filenames are that need renaming because I know I don't conform to the most popular method of site - date - title

**Comment by SgtBatten** [comment]
@kamuk90 please see if you can configure this with Linux. 

You should only need to edit the siteConfig file I think.

**Comment by fritz276** [comment]
Hi, I am trying to get this to work on FreeBSD (FreeNAS Server). I try to run it manually first, but somehow, what did I do wrong? My command from command line was like:

python2.7 pa_renamer_post.py /download/pr0n_clips/Vixen.19.07.28.Riley.Steele.XXX.1080p.MP4-KTR/

[I have a lof of unmatched files from the old data18-content script, and I am too lazy to match individually, so I'd like to get this working. Especially for sabnzbd scripts, since nowadays, with the scene ID gets more and more common]

2019-08-03 17:09:20,132 pa_renamer   INFO     Starting to process: /download/Nubiles.19.08.03.Veronica.Leal.Sexy.Sweet.XXX.1080p.MP4-KTR/
2019-08-03 17:09:20,133 pa_renamer   DEBUG    Full shoot dict:
2019-08-03 17:09:20,133 pa_renamer   DEBUG    None
2019-08-03 17:09:20,133 pa_renamer   CRITICAL No match found for dir: /download/Nubiles.19.08.03.Veronica.Leal.Sexy.Sweet.XXX.1080p.MP4-KTR/
2019-08-03 17:09:42,797 pa_renamer   INFO     Starting to process: /download/Nubiles.19.08.03.Veronica.Leal.Sexy.Sweet.XXX.1080p.MP4-KTR
2019-08-03 17:09:42,798 pa_renamer   DEBUG    Full shoot dict:
2019-08-03 17:09:42,798 pa_renamer   DEBUG    None
2019-08-03 17:09:42,798 pa_renamer   CRITICAL No match found for dir: /download/Nubiles.19.08.03.Veronica.Leal.Sexy.Sweet.XXX.1080p.MP4-KTR
2019-08-03 17:11:10,329 pa_renamer   INFO     Starting to process: /download/Nubiles.19.08.03.Veronica.Leal.Sexy.Sweet.XXX.1080p.MP4-KTR
2019-08-03 17:11:10,330 pa_renamer   DEBUG    Full shoot dict:
2019-08-03 17:11:10,330 pa_renamer   DEBUG    None
2019-08-03 17:11:10,331 pa_renamer   CRITICAL No match found for dir: /download/Nubiles.19.08.03.Veronica.Leal.Sexy.Sweet.XXX.1080p.MP4-KTR
2019-08-03 17:12:36,079 pa_renamer   INFO     Starting to process: /download/MommysGirl.19.07.06.Adriana.Chechik.And.Elexis.Monroe.Collateral.Squirtage.XXX.1080p.MP4-KTR/
2019-08-03 17:12:36,080 pa_renamer   DEBUG    Full shoot dict:
2019-08-03 17:12:36,080 pa_renamer   DEBUG    None
2019-08-03 17:12:36,080 pa_renamer   CRITICAL No match found for dir: /download/MommysGirl.19.07.06.Adriana.Chechik.And.Elexis.Monroe.Collateral.Squirtage.XXX.1080p.MP4-KTR/
2019-08-03 17:13:44,954 pa_renamer   INFO     Starting to process: /download/pr0n_clips/Vixen.19.07.28.Riley.Steele.XXX.1080p.MP4-KTR
2019-08-03 17:13:44,956 pa_renamer   DEBUG    Full shoot dict:
2019-08-03 17:13:44,956 pa_renamer   DEBUG    None
2019-08-03 17:13:44,956 pa_renamer   CRITICAL No match found for dir: /download/pr0n_clips/Vixen.19.07.28.Riley.Steele.XXX.1080p.MP4-KTR
2019-08-03 17:15:47,091 pa_renamer   INFO     Starting to process: /download/pr0n_clips/Vixen.19.07.28.Riley.Steele.XXX.1080p.MP4-KTR
2019-08-03 17:15:47,092 pa_renamer   DEBUG    Full shoot dict:
2019-08-03 17:15:47,092 pa_renamer   DEBUG    None
2019-08-03 17:15:47,092 pa_renamer   CRITICAL No match found for dir: /download/pr0n_clips/Vixen.19.07.28.Riley.Steele.XXX.1080p.MP4-KTR
2019-08-03 17:16:04,819 pa_renamer   INFO     Starting to process: /download/pr0n_clips/Vixen.19.07.28.Riley.Steele.XXX.1080p.MP4-KTR
2019-08-03 17:16:04,821 pa_renamer   DEBUG    Full shoot dict:
2019-08-03 17:16:04,821 pa_renamer   DEBUG    None
2019-08-03 17:16:04,821 pa_renamer   CRITICAL No match found for dir: /download/pr0n_clips/Vixen.19.07.28.Riley.Steele.XXX.1080p.MP4-KTR
2019-08-03 17:17:01,763 pa_renamer   INFO     Starting to process: /download/pr0n_clips/Vixen.19.07.28.Riley.Steele.XXX.1080p.MP4-KTR/
2019-08-03 17:17:01,765 pa_renamer   DEBUG    Full shoot dict:
2019-08-03 17:17:01,765 pa_renamer   DEBUG    None
2019-08-03 17:17:01,765 pa_renamer   CRITICAL No match found for dir: /download/pr0n_clips/Vixen.19.07.28.Riley.Steele.XXX.1080p.MP4-KTR/

**Comment by josst10** [comment]
I didn't want to ask because SgtBatten is doing so much and this seems like a side project but I'm having some trouble too. I'll be watching for any answers.

**Comment by SgtBatten** [comment]
@josst10 also on Linux?

I use windows so I need people to test Linux for me

Seems the initial regex match is failing for @fritz276

I will investigate.

**Comment by SgtBatten** [comment]
Hmm no the Regex works fine. 

Please enable debug in siteConfig.py and try one folder again.

**Comment by SgtBatten** [comment]
@fritz276
Try calling it without the trailing /

**Comment by fritz276** [comment]
BÄM! I dont know if it I pulled the last ("/") commit already, but without the leading / it WORKED!

python /usr/local/sabnzbd/script/pa_renamer_post.py Vixen.19.08.02.Jill.Kassidy.And.Athena.Faris.XXX.MP4-SDCLiP
INFO:pa_renamer: Starting to process: Vixen.19.08.02.Jill.Kassidy.And.Athena.Faris.XXX.MP4-SDCLiP
DEBUG:pa_renamer: dryrun: False batch: False cleanup: True mediainfo: False mediainfo2: False debug: True use_filename: False
INFO:patools:The Dir is: Vixen.19.08.02.Jill.Kassidy.And.Athena.Faris.XXX.MP4-SDCLiP
DEBUG:patools:Date string determined to be: 2019-08-02 
DEBUG:pa_renamer:Full shoot dict:
DEBUG:pa_renamer:{'date': '2019-08-02', 'studio': 'Vixen', 'filename_title': 'Jill Kassidy And Athena Faris'}
DEBUG:pa_renamer: Before overrides the name is : Vixen - Jill Kassidy And Athena Faris (2019-08-02).mp4
DEBUG:siteOverrides: Before:
DEBUG:siteOverrides:    Site: Vixen
DEBUG:siteOverrides:    Dir: Vixen.19.08.02.Jill.Kassidy.And.Athena.Faris.XXX.MP4-SDCLiP
DEBUG:siteOverrides:    Actor: filleractor
DEBUG:siteOverrides:    Title: Jill Kassidy And Athena Faris
DEBUG:siteOverrides:    Date: 2019-08-02
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.vixen.com:443
DEBUG:urllib3.connectionpool:https://www.vixen.com:443 "GET /search?q=Jill%20Kassidy%20And%20Athena%20Faris HTTP/1.1" 403 None
INFO:siteOverrides:No match found in getRename
DEBUG:pa_renamer: The filetype is: mp4
DEBUG:pa_renamer: After:
DEBUG:pa_renamer:    New directory: Vixen.19.08.02.Jill.Kassidy.And.Athena.Faris.XXX.MP4-SDCLiPNew\Vixen
DEBUG:pa_renamer:    New file name: Vixen - Jill Kassidy And Athena Faris (2019-08-02).mp4
INFO:pa_renamer: Renaming/Moving from: Vixen.19.08.02.Jill.Kassidy.And.Athena.Faris.XXX.MP4-SDCLiP/Vixen.19.08.02.Jill.Kassidy.And.Athena.Faris.XXX.MP4-SDCLiP.mp4 --> Vixen.19.08.02.Jill.Kassidy.And.Athena.Faris.XXX.MP4-SDCLiPNew\Vixen/Vixen - Jill Kassidy And Athena Faris (2019-08-02).mp4
INFO:pa_renamer: Empty Directory Deleted
INFO:pa_renamer: Successful

I will continue testing now with different files and report back! Thanks for your outstanding and quick response!

**Comment by SgtBatten** [comment]
it was definitely the latest commit that was the primary fix as linux and windows have different path structures and I needed to add a linux version which was completely missing before 10 mins ago.
i think the trailing slash also was not helping though. 

Just seeing your slashes change direction though. is that causing issues?

e.g ```New\Vixen/Vixen```

**Comment by fritz276** [comment]
root@sonarr:/download/pr0n_clips # python /usr/local/sabnzbd/script/pa_renamer_post.py ShareMyBF.18.07.31.Allesandra.Snow.And.Zoey.Monroe.Submissive.Sex.Slave.XXX.1080p.MP4-KTR
INFO:pa_renamer: Starting to process: ShareMyBF.18.07.31.Allesandra.Snow.And.Zoey.Monroe.Submissive.Sex.Slave.XXX.1080p.MP4-KTR
DEBUG:pa_renamer: dryrun: False batch: False cleanup: True mediainfo: False mediainfo2: False debug: True use_filename: False
INFO:patools:The Dir is: ShareMyBF.18.07.31.Allesandra.Snow.And.Zoey.Monroe.Submissive.Sex.Slave.XXX.1080p.MP4-KTR
DEBUG:patools:Date string determined to be: 2018-07-31 
DEBUG:pa_renamer:Full shoot dict:
DEBUG:pa_renamer:{'date': '2018-07-31', 'studio': 'ShareMyBF', 'filename_title': 'Allesandra Snow And Zoey Monroe Submissive Sex Slave'}
DEBUG:pa_renamer: Before overrides the name is : ShareMyBF - Allesandra Snow And Zoey Monroe Submissive Sex Slave (2018-07-31).mp4
DEBUG:siteOverrides: Before:
DEBUG:siteOverrides:    Site: ShareMyBF
DEBUG:siteOverrides:    Dir: ShareMyBF.18.07.31.Allesandra.Snow.And.Zoey.Monroe.Submissive.Sex.Slave.XXX.1080p.MP4-KTR
DEBUG:siteOverrides:    Actor: filleractor
DEBUG:siteOverrides:    Title: Allesandra Snow And Zoey Monroe Submissive Sex Slave
DEBUG:siteOverrides:    Date: 2018-07-31
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.mofos.com:443
DEBUG:urllib3.connectionpool:https://www.mofos.com:443 "GET /scenes?page=1&site=201 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.mofos.com:443
DEBUG:urllib3.connectionpool:https://www.mofos.com:443 "GET /scenes?page=2&site=201 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.mofos.com:443
DEBUG:urllib3.connectionpool:https://www.mofos.com:443 "GET /scenes?page=3&site=201 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.mofos.com:443
DEBUG:urllib3.connectionpool:https://www.mofos.com:443 "GET /scenes?page=4&site=201 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.mofos.com:443
DEBUG:urllib3.connectionpool:https://www.mofos.com:443 "GET /scenes?page=5&site=201 HTTP/1.1" 200 None
DEBUG:pa_renamer: The filetype is: mp4
DEBUG:pa_renamer: After:
DEBUG:pa_renamer:    New directory: ShareMyBF.18.07.31.Allesandra.Snow.And.Zoey.Monroe.Submissive.Sex.Slave.XXX.1080p.MP4-KTRShare My BF
DEBUG:pa_renamer:    New file name: ShareMyBF - 3046111 - Submissive Sex Slave (2018-07-31).mp4
INFO:pa_renamer: Renaming/Moving from: ShareMyBF.18.07.31.Allesandra.Snow.And.Zoey.Monroe.Submissive.Sex.Slave.XXX.1080p.MP4-KTR/sharemybf.18.07.31.allesandra.snow.and.zoey.monroe.submissive.sex.slave.mp4 --> ShareMyBF.18.07.31.Allesandra.Snow.And.Zoey.Monroe.Submissive.Sex.Slave.XXX.1080p.MP4-KTRShare My BF/ShareMyBF - 3046111 - Submissive Sex Slave (2018-07-31).mp4
INFO:pa_renamer: Empty Directory Deleted
INFO:pa_renamer: Successful

Wow. Thats so cool. 
ls -la ShareMyBF.* | wc -l
342

Now I wont have to manually match those 342 with SceneID :-)

The slashes (New\Vixen/Vixen) is just ugly because I didnt save my last changes to Siteconfig with guthub when pulling you latest changes. It is just a beauty thing which I will fix in the config file.

**Comment by SgtBatten** [comment]
Awesome. 

If you are going back a long way then you may want to increase the range of the page numbers in  siteOverrides temporarily. Once old content is done it wont matter but if stuff is older than what i have defaulted to (10 pages of history for most sites) it wont get the sceneID or title for those ones.

**Comment by fritz276** [comment]
I am now going to try to implement it with the sabnzbd script and test if that works (might be a bite more of a struggle), also, try to work with better siteConfig parameters. Will get back to you!

**Comment by SgtBatten** [comment]
Nah it's easy.

Put these in your existing sabnzbd scripts folder. then it will appear as a normal postprocessing option

image

**Comment by fritz276** [comment]
Works! Only thing I had to change was the line in pa_renamer_post.py where my python is located!

**Comment by SgtBatten** [comment]
At the top of the file? Windows doesn't use it so I wasn't sure what to put :)

**Comment by fritz276** [comment]
Yeah, the first line!

**Comment by SgtBatten** [comment]
I find if the file is the first one in a folder Plex tries to match using the folder name. After that though it seems to work fine.

**Comment by fritz276** [comment]
Cant I have the option to not rename the filename, but to rename the directory? (and the file). Maybe I can work with the normal sabnzbd postprocessing.

**Comment by SgtBatten** [comment]
You can move all the ones that are not matching out to your sabnzbd downloads folder. Get Plex to do a scan so it's thinks they are deleted. Then run the script on the stuff in the SAB downloads folder and provided your sitelist in siteConfig file is setup for it, it will move them back to Plex and Plex should match

**Comment by fritz276** [comment]
Could you add Digitalplayground (because of SceneID?)

**Comment by kamuk90** [comment]
Can you post some instruction please ;(

**Comment by SgtBatten** [comment]
@kamuk90 i moved the instructions out of the individual files and made a readme. Do you need further clarification?

**Comment by kamuk90** [comment]
@SgtBatten thx a lot
I can’t recognize several video files from one folder for one studio at once (ex Brazzers)
Coz the data is taken from the name of the folder that contains one video file
I don’t want to create so many folders, to the fact that I'm not fully understand with the terminal

**Comment by SgtBatten** [comment]
@kamuk90 this is what the use_filename option is for. Batch processing multiple files from one folder. 

I'll add mention of it in the readme

**Comment by kamuk90** [comment]
My structure:
Pron Sorted **/** Vixen **/** VIXEN - Liya Silver - Alone In Mykonos.mp4 | VIXEN - Little Caprice - Fashion Appreciation.mp4

```
admin@NASBOX:/volume1/video/Pron Sorted/Vixen$ python /volume1/docker/scripts/pa_renamer_post.py -n Vixen
Using FileName.
INFO:pa_renamer: Starting to process: Vixen
DEBUG:pa_renamer: Variables:
DEBUG:pa_renamer: dryrun: False, batch: False, cleanup: True, mediainfo: False, mediainfo2: False, use_filename: True
Traceback (most recent call last):
  File "/volume1/docker/scripts/pa_renamer_post.py", line 191, in <module>
    main()
  File "/volume1/docker/scripts/pa_renamer_post.py", line 72, in main
    for item in os.listdir(dir):
OSError: [Errno 2] No such file or directory: 'Vixen'

admin@NASBOX:/volume1/video/Pron Sorted/Vixen$ cd ..

admin@NASBOX:/volume1/video/Pron Sorted$ python /volume1/docker/scripts/pa_renamer_post.py -n /Vixen
Using FileName.
INFO:pa_renamer: Starting to process: /Vixen
DEBUG:pa_renamer: Variables:
DEBUG:pa_renamer: dryrun: False, batch: False, cleanup: True, mediainfo: False, mediainfo2: False, use_filename: True
Traceback (most recent call last):
  File "/volume1/docker/scripts/pa_renamer_post.py", line 191, in <module>
    main()
  File "/volume1/docker/scripts/pa_renamer_post.py", line 72, in main
    for item in os.listdir(dir):
OSError: [Errno 2] No such file or directory: '/Vixen'

admin@NASBOX:/volume1/video/Pron Sorted$ cd Vixen

admin@NASBOX:/volume1/video/Pron Sorted/Vixen$ python /volume1/docker/scripts/pa_renamer_post.py -n
usage: pa_renamer_post.py [-h] [-d] [-b] [-c] [-m] [-m2] [-n] directory
pa_renamer_post.py: error: too few arguments
```

**Comment by SgtBatten** [comment]
It relies entirely on date matches so they won't work sorry

**Comment by fritz276** [comment]
You should add in the doc that the .bat file does not work on linux (of course). Unfortunately, I cant make a shell script from the .bat file.

**Comment by SgtBatten** [comment]
@fritz276 it's just a simple for loop that runs through the given source folder. We can probably whip something up in python that takes care of windows and Linux I just don't have time right now

**Comment by fritz276** [comment]
@SgtBatten yeah, I am sure you can do that in python, too. Just get back to it, when you have the time. Thanks for your great work anyways!

**Comment by fritz276** [comment]
Hmm. Big Problem, wrong match, cant exactly say, since when:


INFO:pa_renamer: Starting to process: RKPrime.19.08.22.Alyssia.Kent.Kings.Spa.Alyssia.XXX.1080p.MP4-KTR
DEBUG:pa_renamer: Variables:
DEBUG:pa_renamer: dryrun: False, batch: False, cleanup: True, mediainfo: False, mediainfo2: False, use_filename: False
INFO:patools:The Dir is: RKPrime.19.08.22.Alyssia.Kent.Kings.Spa.Alyssia.XXX.1080p.MP4-KTR
DEBUG:patools:Date string determined to be: 2019-08-22 
DEBUG:pa_renamer:Full shoot dict:
DEBUG:pa_renamer:{'date': '2019-08-22', 'studio': 'RKPrime', 'filename_title': 'Alyssia Kent Kings Spa Alyssia'}
DEBUG:pa_renamer: Before overrides the name is : RKPrime - Alyssia Kent Kings Spa Alyssia (2019-08-22).mp4
DEBUG:siteOverrides: Before:
DEBUG:siteOverrides:    Site: RKPrime
DEBUG:siteOverrides:    Dir: RKPrime.19.08.22.Alyssia.Kent.Kings.Spa.Alyssia.XXX.1080p.MP4-KTR
DEBUG:siteOverrides:    Actor: filleractor
DEBUG:siteOverrides:    Title: Alyssia Kent Kings Spa Alyssia
DEBUG:siteOverrides:    Date: 2019-08-22
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.realitykings.com
DEBUG:urllib3.connectionpool:https://www.realitykings.com:443 "GET /scenes?page=1&site= HTTP/1.1" 200 None
DEBUG:pa_renamer: The filetype is: mp4
DEBUG:pa_renamer: After:
DEBUG:pa_renamer:    New directory: RKPrime.19.08.22.Alyssia.Kent.Kings.Spa.Alyssia.XXX.1080p.MP4-KTR
DEBUG:pa_renamer:    New file name: RKPrime - 4392426 - Bubble Bath Babes (2019-08-22).mp4
INFO:pa_renamer: Renaming/Moving from: RKPrime.19.08.22.Alyssia.Kent.Kings.Spa.Alyssia.XXX.1080p.MP4-KTR/rkprime.19.08.22.alyssia.kent.kings.spa.alyssia.mp4 --> RKPrime.19.08.22.Alyssia.Kent.Kings.Spa.Alyssia.XXX.1080p.MP4-KTR/RKPrime - 4392426 - Bubble Bath Babes (2019-08-22).mp4
DEBUG:pa_renamer: The filetype is: sfv
INFO:pa_renamer: Removed: rkprime.19.08.22.alyssia.kent.kings.spa.alyssia.sfv
INFO:pa_renamer: Successful

**Comment by SgtBatten** [comment]
Is there two scenes on that date?

**Comment by fritz276** [comment]
Yeah.

**Comment by SgtBatten** [comment]
It should eb a simple fix if it is due to being two scenes on the date. I've done it for some other sites already. I'll get to it when i can

**Comment by SgtBatten** [comment]
@fritz276 I have fixed that issue now i believe.

Because reality kings has so many sub sites i have not individually mapped them all so for rkprime it is searching the ALL sites pages. I have added an extra check to look at the sub site listed also which should prevent this from happening to you.

**Comment by fritz276** [comment]
Great, I will check it out this weekend and get back to you!

Gesendet von Yahoo Mail für iPhone


Am Freitag, September 27, 2019, 10:39 PM schrieb SgtBatten <notifications@github.com>:


@fritz276 I have fixed that issue now i believe.

Because reality kings has so many sub sites i have not individually mapped them all so for rkprime it is searching the ALL sites pages. I have added an extra check to look at the sub site listed also which should prevent this from happening to you.

**Comment by fritz276** [comment]
> @fritz276 I have fixed that issue now i believe.

root@sonarr:/usr/local/sabnzbd/script # ./pa_renamer_post.py /download/pr0n_clips/RKPrime.19.09.27.Lezley.Zen.And.Sofie.Marie.Dungeons.And.MILFs.XXX.1080p.MP4-KTR
INFO:pa_renamer: Starting to process: /download/pr0n_clips/RKPrime.19.09.27.Lezley.Zen.And.Sofie.Marie.Dungeons.And.MILFs.XXX.1080p.MP4-KTR
DEBUG:pa_renamer: Variables:
DEBUG:pa_renamer: dryrun: False, batch: False, cleanup: True, mediainfo: False, mediainfo2: False, use_filename: False
INFO:patools:The Dir is: /download/pr0n_clips/RKPrime.19.09.27.Lezley.Zen.And.Sofie.Marie.Dungeons.And.MILFs.XXX.1080p.MP4-KTR
DEBUG:patools:Date string determined to be: 2019-09-27 
DEBUG:pa_renamer:Full shoot dict:
DEBUG:pa_renamer:{'date': '2019-09-27', 'studio': 'RKPrime', 'filename_title': 'Lezley Zen And Sofie Marie Dungeons And MILFs'}
DEBUG:pa_renamer: Before overrides the name is : RKPrime - Lezley Zen And Sofie Marie Dungeons And Milfs (2019-09-27).mp4
DEBUG:siteOverrides: Before:
DEBUG:siteOverrides:    Site: RKPrime
DEBUG:siteOverrides:    Dir: /download/pr0n_clips/RKPrime.19.09.27.Lezley.Zen.And.Sofie.Marie.Dungeons.And.MILFs.XXX.1080p.MP4-KTR
DEBUG:siteOverrides:    Actor: filleractor
DEBUG:siteOverrides:    Title: Lezley Zen And Sofie Marie Dungeons And MILFs
DEBUG:siteOverrides:    Date: 2019-09-27
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.realitykings.com:443
DEBUG:urllib3.connectionpool:https://www.realitykings.com:443 "GET /scenes?page=1&site= HTTP/1.1" 200 None
Traceback (most recent call last):
  File "./pa_renamer_post.py", line 185, in <module>
    main()
  File "./pa_renamer_post.py", line 73, in main
    success = renameShoot(shoot, dir, dir, dryrun, cleanup, mediainfo, mediainfo2, use_filename)
  File "./pa_renamer_post.py", line 103, in renameShoot
    correctName = siteOverrides.getRename(shoot['studio'], "filleractor", shoot['filename_title'], shoot['date'])
  File "/usr/local/sabnzbd/script/siteOverrides.py", line 210, in getRename
    releaseSite = detailsPageElements.xpath('//a[@class="sc-11m21lp-0-n jRqcyg"]/div/div[position()=2]/text()')[i].strip()
IndexError: list index out of range

**Comment by SgtBatten** [comment]
@fritz276 sorry about that, typo fixed

**Comment by josst10** [comment]
This is really cool and I love it. However, when I process some test files from RK Prime and Big Naturals which are listed on the sitelist, I am getting a rename with no sceneID. This is an example that is representative of how all files are being renamed. 

originalFolderName = bignaturals.15.01.28.shae.summers.squeeze.and.tease
originalFileName = bignaturals.15.01.28.shae.summers.squeeze.and.tease.mp4

newFileName = bignaturals - Shae Summers Squeeze And Tease (2015-01-28).mp4

I have tried many sites with the same results. Any ideas? I should be expecting a sceneID, no? Thanks!

**Comment by SgtBatten** [comment]
That looks to me like it is not finding a match. given the date is 2015 I suspect it is beyond the 10 pages it is set to search. I am looking at the code now to make sure

**Comment by SgtBatten** [comment]
@josst10 

Confirmed it.

The code searches the first 9 pages of results. Your example scene is on page 10.

Temporarily editing siteOverrides line 200 to ```for pagenumber in range(10,11):``` resulted in the sceneID and correct rename occurring.

feel free to extend the ranges of any sites when you are doing old collections. for new scenes the original range will catch them.

**Comment by fritz276** [comment]
> @fritz276 sorry about that, typo fixed

Yeah, works now, thanks! I really like your script. I wish it would be extended for more sites!

**Comment by josst10** [comment]
WOrks for me too. For my money, this provides more satisfaction than the plug-in itself. Thanks so much!

**Pull request merged**
