### PR TITLE
Fix site search

### PR DESCRIPTION
**Pull request by DirtyRacer1337**
Now it's works for `JAY's POV`

i just added
```python
try:
    # some code
except:
    pass
```
because it gives index error

I also added new method for site search by using `startswith()`, works great on my tests.

### CODE REVIEW

**Comment by claygoldfinch** [comment]
Did a bit of testing with sites with spaces in their names. The agent will match the file with the correct site (already working better than it currently does, nicely done!) but then won't strip the sitename from the search term. Here's a log:

2020-01-21 21:37:40,657 (433c) :  INFO (logkit:16) - *******MEDIA TITLE****** Viv Thomas - Feeling Festive
2020-01-21 21:37:40,657 (433c) :  INFO (logkit:16) - Getting Search Settings for: Viv Thomas - Feeling Festive
2020-01-21 21:37:40,657 (433c) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Viv Thomas Feeling Festive
2020-01-21 21:37:40,667 (433c) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Viv Thomas Feeling Festive
2020-01-21 21:37:40,668 (433c) :  INFO (logkit:16) - ^^^^^^^ siteID: 623
2020-01-21 21:37:40,668 (433c) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-01-21 21:37:40,670 (433c) :  INFO (logkit:16) - viv thoma vs vivthomas
2020-01-21 21:37:40,670 (433c) :  INFO (logkit:16) - 5
2020-01-21 21:37:40,670 (433c) :  INFO (logkit:16) - 7
2020-01-21 21:37:40,670 (433c) :  INFO (logkit:16) - searchTitle (before date processing): Viv Thomas Feeling Festive
2020-01-21 21:37:40,670 (433c) :  INFO (logkit:16) - Search Title: Viv Thomas Feeling Festive
2020-01-21 21:37:40,670 (433c) :  INFO (logkit:16) - Viv%20Thomas%20Feeling%20Festive
2020-01-21 21:37:40,733 (433c) :  DEBUG (networking:143) - Requesting 'https://www.vivthomas.com/search/Viv%20Thomas%20Feeling%20Festive/relevance/1'
2020-01-21 21:37:41,563 (433c) :  DEBUG (networking:143) - Requesting 'https://www.vivthomas.com/search/Viv%20Thomas%20Feeling%20Festive/relevance/2'
2020-01-21 21:37:42,381 (433c) :  DEBUG (runtime:88) - Sending packed state data (1928 bytes)
2020-01-21 21:37:42,381 (433c) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes

**Comment by DirtyRacer1337** [comment]
Strange code, but it's working on your example, I tried to make it universal and not to break that we already have.

**Comment by DirtyRacer1337** [comment]
Now it's can be a problem with two numbers, it's converted `123 456` to `123456`, but it's probably never happen

**Comment by claygoldfinch** [comment]
Haven't heard from @SgtBatten but this seems to be working per my tests. Merging.

**Pull request merged**
