### PR TITLE
Added support for DefeatedXXX, DefeatedSexFight and XVirtual

### PR DESCRIPTION
**Pull request by PowerModder**
Hello! So first time trying to make something on my own using templates and add support to a site using Xpath etc. If someone can re-factor the code please do so. 

DefeatedXXX and DefeatedSexfight
Successfully recovers Title, Date, Description (short version), Rating, Label, Posters and Backgrounds for old and new videos of both sites. (Old videos used another format for posters/background).
The title of the video should be as follows:
SiteName - Title
SiteName - YYYY-MM-DD - Title
SiteName - Title - YYYY-MM-DD
For me all the above are working!
------------------------------------------------------------------------------------------------------------------------------------
XVirtual
Successfully recovers Title, Description (long version), Genres, Label, Posters and Backgrounds for XVirtual site. Site doesn't provide date or model information. :( 
The title of the video should be as follows:
SiteName - Title
You can skip the in 180 degrees part.

### CODE REVIEW

**Comment by DirtyRacer1337** [comment]
1. `siteDefeated` can be combined in one file
2. if site doesn't provide date use it from file name, like this
```python
releaseDate = parse(searchDate).strftime('%Y-%m-%d') if searchDate else ''
```
and don't forget to exclude it from scoring
3. replace `String.Encode` and `String.Decode` to `PAutils.Encode` and `PAutils.Decode` and import `PAutils`

**Comment by PowerModder** [comment]
Hello,
1. How it can combined into one file when they have different URL's for search and as site?
2. Site provides Date and using SiteName - YYYY-MM-DD - Title works 100%. But SiteName - Title sometimes returns results but doesn't automatically choose one.
3. So i Just replace those functions with PAUtils functions and just import PAutils at the start of the file.
Sorry, but it was my first time doing it.

**Comment by DirtyRacer1337** [comment]
1.
```python
elif searchSiteID == 895 or searchSiteID == 896:
```
2.
```python
try:
    releaseDate3 = searchResult.xpath('//meta[@itemprop="datePublished"]')[i].get('content').split("T")
    releaseDate = releaseDate3[0].strip()
    Log("releaseDate: " +releaseDate)
except:
    releaseDate = ""
    Log("No date found (DefeatedSexFight)")
if searchDate:
    score = 100 - Util.LevenshteinDistance(searchDate, releaseDate)
else:
    score = 100 - Util.LevenshteinDistance(searchTitle.lower(), titleNoFormatting.lower())
```
You not check if `releaseDate` is empty in scoring
Why it should be empty if you can fill it by `searchDate`
3. Yes, it's just replace Base64 encoding by Base58

**Comment by DirtyRacer1337** [comment]
Dublicated lines
```python
##############################################################
## Cleanup Genres and Add
Log("Genres")
movieGenres.processGenres(metadata)
```

**Comment by PowerModder** [comment]
1. Understood I can combine the same file as for example multiple site at Kink.
2. I used Badoink's py as a template. It had similar structure. I don't understand very much here.
What I understand I am doing ( :P ) is for every result i get the date and if there is no date i have releaseDate="" and then use it to manipulate the score. At logs it gives a 'right result' how it should be.
3.OK
4. Yes for duplicate stupid mistake

**Comment by PowerModder** [comment]
1 - I combined both sites under one Defeated.py and used the technique you mention.
3 - I replaced String.Decode and String.Encode with PAutils.Decode and PAutils.Encode and import PAutils
4 - I fixed the duplicate issue to my file.

2 - I still don't get what I have done wrong there :( If you can fix it as an example. Basically what i intented to do is to get every result date from the query and compare it with the date that my file has.

Thanks for the help by the way.

P.S I have 100% right matching to my files because i checked it again to see if everything was still working. I deleted and re-enter the library to force again the matching and all files were matched correctly.

P.S.2 Because I see other guys have done pull request to support sites and we have a 'conflict' to searchsites file maybe it is better to fix our files so no 'override' will occur. For example, now my file has no conflict with base branch butt if you merged Ximilite support then we have a conflict.

**Comment by PowerModder** [comment]
I am noob with Github. Everytime I want to synchronize my repo with recent changes (merges) to those repo i deleted and re-forked it... Anyway close and re-open, added other sites too

**Pull request closed without merging**
