### PR TITLE
AmateurCFNM & PureCFNM

### PR DESCRIPTION
**Pull request by jamesalexw**
Added support for AmateurCFNM and PureCFNM.

### CODE REVIEW

**Comment by claygoldfinch** [comment]
Probably better off deleting your fork and creating a new one with your changes - there's a lot of changed code and files here that aren't relevant to adding AmateurCFNM and PureCFNM. If you're still having trouble with passing variables from the search function to the update function it's because you aren't replacing "?" and "/". You need to do that in the search function. Then, in the update function, convert the variable to it's original state. See videoBG as an example. 

Also, no need to create separate files for PureCFNM and AmateurCFNM if the code is entirely the same. Rename one of the files to networkPureCFNM and add support for all the PureCFNM sites (https://www.purecfnm.com/sites/).

**Comment by DirtyRacer1337** [comment]
Also read this, [Syncing a fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork), that's help you with keeping your master branch updated.

**Comment by jamesalexw** [comment]
I'd already downloaded the latest ZIP, copied the files into my branch and re-added my changes so this does include all of the latest updates.

I'll have a go at doing the network version for PureCFNM but like I said before I'm learning so I'll need to go away and do that. At least this adds support for those sites and I can refine it as I go.

**Comment by jamesalexw** [comment]
I'll close this pull request and open a new one with the updated fixes for special characters. I'll work on the other sites and create a network file for them as I go.

**Comment by claygoldfinch** [comment]
@jamesalexw Just FYI (in case this comes up again in the future), best practice would be to delete your fork, refork, and then commit only the files you changed.

**Comment by jamesalexw** [comment]
Do you mean delete the repository from my account? Just wanted to check as the terminology is new to me too.

**Pull request closed without merging**
