### PR TITLE
API support for lots of sites

### LINKED ISSUE #573: Mofos not getting scene description sometimes
Specifically tested on PervsonPatrol scenes, such as: https://www.mofos.com/scene/3023901/busty-neighbor-catches-peeping-tom

### PR DESCRIPTION
**Pull request by DirtyRacer1337**
I finished it faster that I thought. Fixes #573, #577, #580, #587, #591, #592 

Supported sites:
- RealityKings
- Mofos
- Babes
- Twistys
- DigitalPlayground
- SexyHub
- FakeHub
- MileHighMedia
- PropertySex
- TransAngels
- FamilyHookups
- LilHumpers
- BellesaFilms
- FamilySinners
- Transsensual
- Erito
- True Amateurs
- Look At Her Now

### CODE REVIEW

**Comment by claygoldfinch** [comment]
You're better off keeping these as a separate file per site. I understand your thinking here, but it's a total pain to bugfix and test when one site makes changes down the road and none of the others do.

**Comment by DirtyRacer1337** [comment]
They all have the same API for every site, but you probably right, just don't like to see lots duplicate code.

**Comment by claygoldfinch** [comment]
Good point. Screw it, go ahead and combine them all. You're right, if they're using the same API it's far less likely for the search function to break for just one site down the road.

If any changes are made to scene pages in the future we can create different update functions in the network1service file.

I'll come up with a list of all the sites the agent scrapes that uses the API.

One thing to keep in mind is that some sites support DVD release while others only support scene releases.

**Comment by claygoldfinch** [comment]
- RealityKings
- Mofos
- Babes
- Twistys
- DigitalPlayground
- SexyHub
- FakeHub
- MileHighMedia
- PropertySex
- TransAngels
- FamilyHookups
- LilHumpers
- BellesaFilms
- FamilySinners
- Transsensual
- Erito
- True Amateurs

You can probably add support for https://www.lookathernow.com, as well.

**Comment by claygoldfinch** [comment]
Doesn't look like full series or movies are working, as they're not indexed in the API.

https://www.digitalplayground.com/movie/4132391/babysitters-2
https://www.digitalplayground.com/series/4358096/better-things-to-do

Perhaps revert to SceneID only for these?

And here's a few scenes I'm having difficulty with:
1.
```
2020-01-21 15:33:09,710 (3a7c) :  INFO (logkit:16) - *******MEDIA TITLE****** DigitalPlayground - 4336331
2020-01-21 15:33:09,710 (3a7c) :  INFO (logkit:16) - Getting Search Settings for: DigitalPlayground - 4336331
2020-01-21 15:33:09,710 (3a7c) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: DigitalPlayground 4336331
2020-01-21 15:33:09,716 (3a7c) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: DigitalPlayground 4336331
2020-01-21 15:33:09,717 (3a7c) :  INFO (logkit:16) - ^^^^^^^ siteID: 328
2020-01-21 15:33:09,717 (3a7c) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-01-21 15:33:09,717 (3a7c) :  INFO (logkit:16) - digitalplayground vs digitalplayground
2020-01-21 15:33:09,717 (3a7c) :  INFO (logkit:16) - 1
2020-01-21 15:33:09,717 (3a7c) :  INFO (logkit:16) - 7
2020-01-21 15:33:09,717 (3a7c) :  INFO (logkit:16) - searchTitle (before date processing): 4336331
2020-01-21 15:33:09,717 (3a7c) :  INFO (logkit:16) - Search Title: 4336331
2020-01-21 15:33:09,717 (3a7c) :  INFO (logkit:16) - 4336331
2020-01-21 15:33:11,072 (3a7c) :  CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': '2019', 'id': '49682', 'name': 'DigitalPlayground - 4336331'} (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ac2afe5f8\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 474, in search
    results = PAsearchSites.network1service.search(results, encodedTitle, title, searchTitle, siteNum, lang, searchByDateActor, searchDate, searchSiteID)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network1service.py", line 49, in search
    subSite = searchResult['collections'][0]['name']
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ac2afe5f8\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2020-01-21 15:33:11,075 (3a7c) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-01-21 15:33:11,075 (3a7c) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```
2. DigitalPlayground - 4358098 - Better Things To Do Episode 6 
Not pulling summary. Also may be better to add this to a collection under the name of the series (Better Things To Do), rather than "Episodes"?

**Comment by claygoldfinch** [comment]
Been playing around with this a bit more. You may want to rely on SceneID a bit less, as it seems to be unreliable. When these sites converted their layout to their current form, multiple pages were often made for each scene - each with a unique SceneID. They seem to be fixing this, but I'm sure many users of the agent have scenes with SceneIDs that are now considered "invalid". For example:

https://www.digitalplayground.com/movie/4134891/cheerleaders
https://www.digitalplayground.com/movie/4132001/cheerleaders

https://www.digitalplayground.com/movie/4142641/stoya-scream
https://www.digitalplayground.com/movie/4157331/stoya-scream

https://www.digitalplayground.com/movie/4142461/stoya-sexual-freak-7
https://www.digitalplayground.com/movie/4159051/stoya-sexual-freak-7

**Comment by claygoldfinch** [comment]
Also, it appears as though DVD covers and actors aren't being scraped for DVD releases. 

Example: https://www.digitalplayground.com/movie/4132001/cheerleaders

**Comment by claygoldfinch** [comment]
```
2020-01-22 14:56:07,588 (3258) :  INFO (logkit:16) - *******MEDIA TITLE****** Digitalplayground 4138761 Stoya Workaholic
2020-01-22 14:56:07,588 (3258) :  INFO (logkit:16) - Getting Search Settings for: Digitalplayground 4138761 Stoya Workaholic
2020-01-22 14:56:07,588 (3258) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Digitalplayground 4138761 Stoya Workaholic
2020-01-22 14:56:07,595 (3258) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Digitalplayground 4138761 Stoya Workaholic
2020-01-22 14:56:07,595 (3258) :  INFO (logkit:16) - ^^^^^^^ siteID: 328
2020-01-22 14:56:07,596 (3258) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-01-22 14:56:07,596 (3258) :  INFO (logkit:16) - digitalplayground vs digitalplayground
2020-01-22 14:56:07,598 (3258) :  INFO (logkit:16) - 1
2020-01-22 14:56:07,598 (3258) :  INFO (logkit:16) - 7
2020-01-22 14:56:07,598 (3258) :  INFO (logkit:16) - searchTitle (before date processing): 4138761 Stoya Workaholic
2020-01-22 14:56:07,598 (3258) :  INFO (logkit:16) - Search Title: 4138761 Stoya Workaholic
2020-01-22 14:56:07,598 (3258) :  INFO (logkit:16) - 4138761%20Stoya%20Workaholic
2020-01-22 14:56:08,805 (3258) :  DEBUG (runtime:88) - Sending packed state data (2812 bytes)
2020-01-22 14:56:08,805 (3258) :  DEBUG (runtime:924) - Response: [200] str, 7952 bytes
2020-01-22 14:56:10,342 (3208) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo1NzkzN3M0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXM1OQpjb20ucGxleGFwcC5hZ2VudHMucGhvZW5peGFkdWx0Oi8vNDEzODc2MXwzMjh8bW92aWU%40bGFuZz1lbnM0Cmd1aWRzMTcKNDEzODc2MXwzMjh8bW92aWVzMgppZHIwCg__
2020-01-22 14:56:10,344 (3208) :  DEBUG (runtime:49) - Received packed state data (960 bytes)
2020-01-22 14:56:10,345 (3208) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo1NzkzN3M0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXM1OQpjb20ucGxleGFwcC5hZ2VudHMucGhvZW5peGFkdWx0Oi8vNDEzODc2MXwzMjh8bW92aWU@bGFuZz1lbnM0Cmd1aWRzMTcKNDEzODc2MXwzMjh8bW92aWVzMgppZHIwCg__
2020-01-22 14:56:10,345 (3208) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.phoenixadult://4138761|328|movie?lang=en
2020-01-22 14:56:10,345 (3208) :  DEBUG (model:234) - Deserializing from C:\Users\thisi\AppData\Local\Plex Media Server\Metadata\Movies\a\c16e3c32895cc2bc6784b6ad4b822f452b6ed67.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2020-01-22 14:56:10,346 (3208) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/57937/tree'
2020-01-22 14:56:10,355 (3208) :  INFO (logkit:16) - ******UPDATE CALLED*******
2020-01-22 14:56:10,355 (3208) :  INFO (logkit:16) - 328
2020-01-22 14:56:10,355 (3208) :  INFO (logkit:16) - ******UPDATE CALLED*******
2020-01-22 14:56:10,947 (3208) :  CRITICAL (core:574) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://4138761|328|movie?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ac2afe5f8\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1089, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 1426, in update
    metadata = PAsearchSites.network1service.update(metadata, siteID, movieGenres, movieActors)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network1service.py", line 103, in update
    tagline = detailsPageElements['collections'][0]['name']
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ac2afe5f8\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2020-01-22 14:56:10,947 (3208) :  DEBUG (model:229) - Serializing to C:\Users\thisi\AppData\Local\Plex Media Server\Metadata\Movies\a\c16e3c32895cc2bc6784b6ad4b822f452b6ed67.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2020-01-22 14:56:10,950 (3208) :  DEBUG (runtime:88) - Sending packed state data (992 bytes)
2020-01-22 14:56:10,950 (3208) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by d2dyno** [comment]
This looks amazing, thank you to both developers for work so hard on updating to API! Any less work manually matching with siteID is very appreciated.

Let me know if I can buy you guys a beer or coffee

**Comment by claygoldfinch** [comment]
```
2020-01-22 20:32:04,361 (960) :  INFO (logkit:16) - *******MEDIA TITLE****** FamilyHookups - 4404863/sexy-teen-pamela-morrison-fucks-her-dirty-hung-uncle-for-some-stress-relief
2020-01-22 20:32:04,361 (960) :  INFO (logkit:16) - Getting Search Settings for: FamilyHookups - 4404863/sexy-teen-pamela-morrison-fucks-her-dirty-hung-uncle-for-some-stress-relief
2020-01-22 20:32:04,361 (960) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: FamilyHookups 4404863/sexy teen pamela morrison fucks her dirty hung uncle for some stress relief
2020-01-22 20:32:04,368 (960) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: FamilyHookups 4404863/sexy teen pamela morrison fucks her dirty hung uncle for some stress relief
2020-01-22 20:32:04,369 (960) :  INFO (logkit:16) - ^^^^^^^ siteID: 759
2020-01-22 20:32:04,369 (960) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-01-22 20:32:04,369 (960) :  INFO (logkit:16) - familyhookups vs familyhookups
2020-01-22 20:32:04,369 (960) :  INFO (logkit:16) - 1
2020-01-22 20:32:04,369 (960) :  INFO (logkit:16) - 7
2020-01-22 20:32:04,371 (960) :  INFO (logkit:16) - searchTitle (before date processing): 4404863/sexy teen pamela morrison fucks her dirty hung uncle for some stress relief
2020-01-22 20:32:04,371 (960) :  INFO (logkit:16) - Search Title: 4404863/sexy teen pamela morrison fucks her dirty hung uncle for some stress relief
2020-01-22 20:32:04,371 (960) :  INFO (logkit:16) - 4404863/sexy%20teen%20pamela%20morrison%20fucks%20her%20dirty%20hung%20uncle%20for%20some%20stress%20relief
2020-01-22 20:32:05,836 (960) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-01-22 20:32:05,836 (960) :  DEBUG (runtime:924) - Response: [200] str, 4620 bytes
2020-01-22 20:32:07,842 (1590) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo1MDMzMHM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXM1OQpjb20ucGxleGFwcC5hZ2VudHMucGhvZW5peGFkdWx0Oi8vNDQwNDg2M3w3NTl8c2NlbmU%40bGFuZz1lbnM0Cmd1aWRzMTcKNDQwNDg2M3w3NTl8c2NlbmVzMgppZHIwCg__
2020-01-22 20:32:07,844 (1590) :  DEBUG (runtime:49) - Received packed state data (2532 bytes)
2020-01-22 20:32:07,845 (1590) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo1MDMzMHM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXM1OQpjb20ucGxleGFwcC5hZ2VudHMucGhvZW5peGFkdWx0Oi8vNDQwNDg2M3w3NTl8c2NlbmU@bGFuZz1lbnM0Cmd1aWRzMTcKNDQwNDg2M3w3NTl8c2NlbmVzMgppZHIwCg__
2020-01-22 20:32:07,845 (1590) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.phoenixadult://4404863|759|scene?lang=en
2020-01-22 20:32:07,845 (1590) :  DEBUG (model:234) - Deserializing from C:\Users\thisi\AppData\Local\Plex Media Server\Metadata\Movies\0\bd45ca67341f7f2344a422059cd8d4bc4e25b15.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2020-01-22 20:32:07,846 (1590) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/50330/tree'
2020-01-22 20:32:07,857 (1590) :  INFO (logkit:16) - ******UPDATE CALLED*******
2020-01-22 20:32:07,857 (1590) :  INFO (logkit:16) - 759
2020-01-22 20:32:07,857 (1590) :  INFO (logkit:16) - ******UPDATE CALLED*******
2020-01-22 20:32:08,724 (1590) :  CRITICAL (core:574) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://4404863|759|scene?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ac2afe5f8\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1089, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 1946, in update
    metadata = PAsearchSites.network1service.update(metadata, siteID, movieGenres, movieActors)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network1service.py", line 138, in update
    movieActors.addActor(actorName, actorPhotoURL)
UnboundLocalError: local variable 'actorPhotoURL' referenced before assignment

2020-01-22 20:32:08,726 (1590) :  DEBUG (model:229) - Serializing to C:\Users\thisi\AppData\Local\Plex Media Server\Metadata\Movies\0\bd45ca67341f7f2344a422059cd8d4bc4e25b15.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2020-01-22 20:32:08,727 (1590) :  DEBUG (runtime:88) - Sending packed state data (2564 bytes)
2020-01-22 20:32:08,727 (1590) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by claygoldfinch** [comment]
Films from SweetheartVideos seem to be added to two collections - SweetHeartVideo and Sweetheart Video.

Two examples:
https://www.milehighmedia.com/movie/4410061/lesbian-analingus-14
https://www.milehighmedia.com/movie/4378142/lesbian-analingus-08

**Comment by claygoldfinch** [comment]
SexyHub & subsites don't appear to be working:

```
2020-01-22 20:45:11,092 (3abc) :  INFO (logkit:16) - *******MEDIA TITLE****** DaneJones - Petite redhead lusts for boyfriend
2020-01-22 20:45:11,092 (3abc) :  INFO (logkit:16) - Getting Search Settings for: DaneJones - Petite redhead lusts for boyfriend
2020-01-22 20:45:11,092 (3abc) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: DaneJones Petite redhead lusts for boyfriend
2020-01-22 20:45:11,099 (3abc) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: DaneJones Petite redhead lusts for boyfriend
2020-01-22 20:45:11,101 (3abc) :  INFO (logkit:16) - ^^^^^^^ siteID: 334
2020-01-22 20:45:11,101 (3abc) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-01-22 20:45:11,101 (3abc) :  INFO (logkit:16) - danejones  vs dane jones
2020-01-22 20:45:11,101 (3abc) :  INFO (logkit:16) - 3
2020-01-22 20:45:11,101 (3abc) :  INFO (logkit:16) - 7
2020-01-22 20:45:11,101 (3abc) :  INFO (logkit:16) - searchTitle (before date processing): Petite redhead lusts for boyfriend
2020-01-22 20:45:11,101 (3abc) :  INFO (logkit:16) - Search Title: Petite redhead lusts for boyfriend
2020-01-22 20:45:11,101 (3abc) :  INFO (logkit:16) - Petite%20redhead%20lusts%20for%20boyfriend
2020-01-22 20:45:11,789 (3abc) :  CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': '2020', 'id': '50330', 'name': 'DaneJones - Petite redhead lusts for boyfriend'} (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ac2afe5f8\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 481, in search
    results = PAsearchSites.network1service.search(results, encodedTitle, title, searchTitle, siteNum, lang, searchByDateActor, searchDate, searchSiteID)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network1service.py", line 39, in search
    data = urllib.urlopen(req).read()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2020-01-22 20:45:11,789 (3abc) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-01-22 20:45:11,789 (3abc) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by claygoldfinch** [comment]
Seems like you can only search for FamilySinners scenes, not movies. Example:
https://www.familysinners.com/series/4361619/stepson-seductions

**Comment by claygoldfinch** [comment]
I think we're pretty close to merging this. I've gone through and tested every site at this point. Really impressive work, thanks for all your time!

**Comment by DirtyRacer1337** [comment]
Looks like I fixed everything

**Comment by ikenbe** [comment]
This would be a huge improvement. Nice work!

**Comment by claygoldfinch** [comment]
> Looks like I fixed everything

Looks like you did! Merging.

**Pull request merged**
