### PR TITLE
Fix Nubiles

### PR DESCRIPTION
**Pull request by scene-switch**
xpath searches within searchResult were missing a `.` so the loop would always return the first result only

### CODE REVIEW

**Comment by LotusBob** [comment]
I hope you will please answer this question.  Do I need to download or replace the PhoenixAdult.bundle every time someone makes a change or adds sites?  I want to learn how to help and improve this great asset.
Thanks

**Comment by scene-switch** [comment]
@LotusBob if you deployed PhoenixAdult.bundle by simply downloading the zip and placing it in your Plex folder, you need to replace the entire PhoenixAdult.bundle each time there is a change to the `[master](https://github.com/PAhelper/PhoenixAdult.bundle)` branch in order to benefit from the fixes included within.

I should note that changes listed under [Pull Requests](https://github.com/PAhelper/PhoenixAdult.bundle/pulls), such as this fix to Nubiles, are proposed changes from third-party developers, and are not part of the downloadable bundle until they are merged into `[master](https://github.com/PAhelper/PhoenixAdult.bundle)`.

**Comment by LotusBob** [comment]
Thank you kindly for your response

**Comment by scene-switch** [comment]
@LotusBob all those pull requests have been merged, so now would be a good time to grab the latest code and replace PhoenixAdult.bundle in your Plex plugins folder.

**Comment by LotusBob** [comment]
Thanks

**Pull request closed without merging**
