### PR TITLE
Search fix for siteVRBangers.py [Site Changed]

### PR DESCRIPTION
**Pull request by pedrolara-boop**
Fixes only the search. The date seems to have been removed from the results page.
Couldn't get the rest to work.

### CODE REVIEW

**Comment by delposibl** [comment]
Duplicate of #466

**Comment by delposibl** [comment]
Fixed this up in #466 
Duplicate of #

**Comment by delposibl** [comment]
#466

**Comment by pedrolara-boop** [comment]
Please check #466 for full fix

**Pull request closed without merging**
