### PR TITLE
pervmom fixes

### PR DESCRIPTION
**Pull request by SgtBatten**

### CODE REVIEW

**Comment by d2dyno** [comment]
Sorry for the confusion. Thumbs up is my way of saying thanks, and I normally comment when I have had the chance to test :smile: that being said, I just tested. I can now use direct url without a prefix slash, however, SceneID is throwing same error from #318:

```
2019-07-26 22:19:05,554 (14edba0da700) :  INFO (__init__:46) - *******MEDIA TITLE****** pervmom 933
2019-07-26 22:19:05,555 (14edba0da700) :  INFO (__init__:53) - Getting Search Settings for: pervmom 933
2019-07-26 22:19:05,555 (14edba0da700) :  INFO (PAsearchSites:887) - mediaTitle w/ possible abbrieviation: pervmom 933
2019-07-26 22:19:05,565 (14edba0da700) :  INFO (PAsearchSites:1063) - mediaTitle w/ possible abbrieviation fixed: pervmom 933
2019-07-26 22:19:05,569 (14edba0da700) :  INFO (PAsearchSites:1078) - ^^^^^^^ siteID: 686
2019-07-26 22:19:05,569 (14edba0da700) :  INFO (PAsearchSites:1080) - ^^^^^^^ Shortening Title
2019-07-26 22:19:05,570 (14edba0da700) :  INFO (PAsearchSites:1081) - pervmom vs pervmom
2019-07-26 22:19:05,570 (14edba0da700) :  INFO (PAsearchSites:1084) - 1
2019-07-26 22:19:05,570 (14edba0da700) :  INFO (PAsearchSites:1133) - 6
2019-07-26 22:19:05,570 (14edba0da700) :  INFO (PAsearchSites:1133) - searchTitle (before date processing): 933
2019-07-26 22:19:05,570 (14edba0da700) :  INFO (__init__:63) - Search Title: 933
2019-07-26 22:19:05,570 (14edba0da700) :  INFO (__init__:72) - 933
2019-07-26 22:19:05,576 (14edba0da700) :  DEBUG (networking:166) - Requesting 'http://www.pervmom.com933/1/1/'
2019-07-26 22:19:05,590 (14edba0da700) :  CRITICAL (agentkit:1014) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': '2019', 'id': '110351', 'name': 'pervmom 933'} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 790, in search
    results = PAsearchSites.sitePervMom.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/sitePervMom.py", line 10, in search
    searchResults = HTML.ElementFromURL(url)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 482, in ElementFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
```

Also there is some fanart error with direct url method (which matches just fine):

```
2019-07-26 22:20:39,449 (14edba0da700) :  INFO (__init__:46) - *******MEDIA TITLE****** pervmom 933/stepmom-pussy-or-bust/jennifer-white
2019-07-26 22:20:39,449 (14edba0da700) :  INFO (__init__:53) - Getting Search Settings for: pervmom 933/stepmom-pussy-or-bust/jennifer-white
2019-07-26 22:20:39,449 (14edba0da700) :  INFO (PAsearchSites:887) - mediaTitle w/ possible abbrieviation: pervmom 933/stepmom pussy or bust/jennifer white
2019-07-26 22:20:39,462 (14edba0da700) :  INFO (PAsearchSites:1063) - mediaTitle w/ possible abbrieviation fixed: pervmom 933/stepmom pussy or bust/jennifer white
2019-07-26 22:20:39,465 (14edba0da700) :  INFO (PAsearchSites:1078) - ^^^^^^^ siteID: 686
2019-07-26 22:20:39,465 (14edba0da700) :  INFO (PAsearchSites:1080) - ^^^^^^^ Shortening Title
2019-07-26 22:20:39,466 (14edba0da700) :  INFO (PAsearchSites:1081) - pervmom vs pervmom
2019-07-26 22:20:39,466 (14edba0da700) :  INFO (PAsearchSites:1084) - 1
2019-07-26 22:20:39,466 (14edba0da700) :  INFO (PAsearchSites:1133) - 6
2019-07-26 22:20:39,466 (14edba0da700) :  INFO (PAsearchSites:1133) - searchTitle (before date processing): 933/stepmom pussy or bust/jennifer white
2019-07-26 22:20:39,467 (14edba0da700) :  INFO (__init__:63) - Search Title: 933/stepmom pussy or bust/jennifer white
2019-07-26 22:20:39,467 (14edba0da700) :  INFO (__init__:72) - 933/stepmom%20pussy%20or%20bust/jennifer%20white
2019-07-26 22:20:39,470 (14edba0da700) :  INFO (sitePervMom:20) - searchTitle.replace: 933/stepmom-pussy-or-bust/jennifer-white
2019-07-26 22:20:39,473 (14edba0da700) :  DEBUG (networking:161) - Fetching 'https://www.pervmom.com/933/stepmom-pussy-or-bust/jennifer-white' from the HTTP cache
2019-07-26 22:20:39,477 (14edba0da700) :  INFO (sitePervMom:24) - curID: https:__www.pervmom.com_933_stepmom-pussy-or-bust_jennifer-white
2019-07-26 22:20:39,485 (14edba0da700) :  DEBUG (runtime:88) - Sending packed state data (14204 bytes)
2019-07-26 22:20:39,485 (14edba0da700) :  DEBUG (runtime:924) - Response: [200] str, 752 bytes
2019-07-26 22:20:42,647 (14edba0da700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoxMTAzNTFzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM1Ck1vdmllczEwCm1lZGlhX3R5cGVzMTEwCmNvbS5wbGV4YXBwLmFnZW50cy5waG9lbml4YWR1bHQ6Ly9odHRwczpfX3d3dy5wZXJ2bW9tLmNvbV85MzNfc3RlcG1vbS1wdXNzeS1vci1idXN0X2plbm5pZmVyLXdoaXRlfDY4Nj9sYW5nPWVuczQKZ3VpZHM2OApodHRwczpfX3d3dy5wZXJ2bW9tLmNvbV85MzNfc3RlcG1vbS1wdXNzeS1vci1idXN0X2plbm5pZmVyLXdoaXRlfDY4NnMyCmlkcjAK
2019-07-26 22:20:42,648 (14edba0da700) :  DEBUG (runtime:49) - Received packed state data (6192 bytes)
2019-07-26 22:20:42,651 (14edba0da700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoxMTAzNTFzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM1Ck1vdmllczEwCm1lZGlhX3R5cGVzMTEwCmNvbS5wbGV4YXBwLmFnZW50cy5waG9lbml4YWR1bHQ6Ly9odHRwczpfX3d3dy5wZXJ2bW9tLmNvbV85MzNfc3RlcG1vbS1wdXNzeS1vci1idXN0X2plbm5pZmVyLXdoaXRlfDY4Nj9sYW5nPWVuczQKZ3VpZHM2OApodHRwczpfX3d3dy5wZXJ2bW9tLmNvbV85MzNfc3RlcG1vbS1wdXNzeS1vci1idXN0X2plbm5pZmVyLXdoaXRlfDY4NnMyCmlkcjAK
2019-07-26 22:20:42,652 (14edba0da700) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.phoenixadult://https:__www.pervmom.com_933_stepmom-pussy-or-bust_jennifer-white|686?lang=en
2019-07-26 22:20:42,654 (14edba0da700) :  DEBUG (model:234) - Deserializing from /config/Library/Application Support/Plex Media Server/Metadata/Movies/a/b3bcd2889da51584c12de3237b626bf93802f6a.bundle/Contents/com.plexapp.agents.phoenixadult/Info.xml
2019-07-26 22:20:42,666 (14edba0da700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/110351/tree'
2019-07-26 22:20:42,675 (14edba0da700) :  INFO (__init__:986) - ******UPDATE CALLED*******
2019-07-26 22:20:42,675 (14edba0da700) :  INFO (__init__:989) - 686
2019-07-26 22:20:42,675 (14edba0da700) :  INFO (sitePervMom:32) - ******UPDATE CALLED*******
2019-07-26 22:20:42,676 (14edba0da700) :  DEBUG (networking:166) - Requesting 'https://www.pervmom.com/933/stepmom-pussy-or-bust/jennifer-white'
2019-07-26 22:20:42,867 (14edba0da700) :  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://https:__www.pervmom.com_933_stepmom-pussy-or-bust_jennifer-white|686?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 1508, in update
    metadata = PAsearchSites.sitePervMom.update(metadata,siteID,movieGenres,movieActors)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/sitePervMom.py", line 79, in update
    fanSite = PAextras.getFanArt("TeamSkeetFans.com", art, actors, actorName, metadata.title, 0)
TypeError: getFanArt() takes exactly 7 arguments (6 given)
```

**Comment by SgtBatten** [comment]
@d2dyno both should be fixed now.

**Comment by d2dyno** [comment]
Now getting these

```
2019-07-27 00:19:08,579 (1467cb9fc700) :  INFO (__init__:46) - *******MEDIA TITLE****** Pervmom 931
2019-07-27 00:19:08,579 (1467cb9fc700) :  INFO (__init__:53) - Getting Search Settings for: Pervmom 931
2019-07-27 00:19:08,579 (1467cb9fc700) :  INFO (PAsearchSites:887) - mediaTitle w/ possible abbrieviation: Pervmom 931
2019-07-27 00:19:08,588 (1467cb9fc700) :  INFO (PAsearchSites:1063) - mediaTitle w/ possible abbrieviation fixed: Pervmom 931
2019-07-27 00:19:08,591 (1467cb9fc700) :  INFO (PAsearchSites:1078) - ^^^^^^^ siteID: 686
2019-07-27 00:19:08,591 (1467cb9fc700) :  INFO (PAsearchSites:1080) - ^^^^^^^ Shortening Title
2019-07-27 00:19:08,591 (1467cb9fc700) :  INFO (PAsearchSites:1081) - pervmom vs pervmom
2019-07-27 00:19:08,591 (1467cb9fc700) :  INFO (PAsearchSites:1084) - 1
2019-07-27 00:19:08,591 (1467cb9fc700) :  INFO (PAsearchSites:1133) - 6
2019-07-27 00:19:08,591 (1467cb9fc700) :  INFO (PAsearchSites:1133) - searchTitle (before date processing): 931
2019-07-27 00:19:08,591 (1467cb9fc700) :  INFO (__init__:63) - Search Title: 931
2019-07-27 00:19:08,592 (1467cb9fc700) :  INFO (__init__:72) - 931
2019-07-27 00:19:08,595 (1467cb9fc700) :  DEBUG (networking:166) - Requesting 'https://www.pervmom.com/931/1/1/'
2019-07-27 00:19:08,798 (1467cb9fc700) :  CRITICAL (agentkit:1014) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': '2019', 'id': '108888', 'name': 'Pervmom 931'} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 790, in search
    results = PAsearchSites.sitePervMom.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/sitePervMom.py", line 12, in search
    titleNoFormatting = searchResult.xpath('//span[@class="p-small red"]')[0].text_content().strip()
UnboundLocalError: local variable 'searchResult' referenced before assignment
```

```
2019-07-27 00:21:49,107 (1467cb9fc700) :  INFO (__init__:46) - *******MEDIA TITLE****** Pervmom 919/fucking-away-the-stepmom-stress
2019-07-27 00:21:49,107 (1467cb9fc700) :  INFO (__init__:53) - Getting Search Settings for: Pervmom 919/fucking-away-the-stepmom-stress
2019-07-27 00:21:49,107 (1467cb9fc700) :  INFO (PAsearchSites:887) - mediaTitle w/ possible abbrieviation: Pervmom 919/fucking away the stepmom stress
2019-07-27 00:21:49,119 (1467cb9fc700) :  INFO (PAsearchSites:1063) - mediaTitle w/ possible abbrieviation fixed: Pervmom 919/fucking away the stepmom stress
2019-07-27 00:21:49,123 (1467cb9fc700) :  INFO (PAsearchSites:1078) - ^^^^^^^ siteID: 686
2019-07-27 00:21:49,123 (1467cb9fc700) :  INFO (PAsearchSites:1080) - ^^^^^^^ Shortening Title
2019-07-27 00:21:49,123 (1467cb9fc700) :  INFO (PAsearchSites:1081) - pervmom vs pervmom
2019-07-27 00:21:49,124 (1467cb9fc700) :  INFO (PAsearchSites:1084) - 1
2019-07-27 00:21:49,124 (1467cb9fc700) :  INFO (PAsearchSites:1133) - 6
2019-07-27 00:21:49,124 (1467cb9fc700) :  INFO (PAsearchSites:1133) - searchTitle (before date processing): 919/fucking away the stepmom stress
2019-07-27 00:21:49,124 (1467cb9fc700) :  INFO (__init__:63) - Search Title: 919/fucking away the stepmom stress
2019-07-27 00:21:49,124 (1467cb9fc700) :  INFO (__init__:72) - 919/fucking%20away%20the%20stepmom%20stress
2019-07-27 00:21:49,128 (1467cb9fc700) :  INFO (sitePervMom:20) - searchTitle.replace: 919/fucking-away-the-stepmom-stress
2019-07-27 00:21:49,130 (1467cb9fc700) :  DEBUG (networking:161) - Fetching 'https://www.pervmom.com/919/fucking-away-the-stepmom-stress' from the HTTP cache
2019-07-27 00:21:49,134 (1467cb9fc700) :  CRITICAL (agentkit:1014) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': '2019', 'id': '100432', 'name': 'Pervmom 919/fucking-away-the-stepmom-stress'} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 790, in search
    results = PAsearchSites.sitePervMom.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/sitePervMom.py", line 22, in search
    titleNoFormatting = searchResult.xpath('//span[@class="p-small red"]')[0].text_content().strip()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
```

**Comment by SgtBatten** [comment]
@d2dyno  thanks.

first one is fixed now. had an extra s in there.

second one is because you don't have the full url, its missing the actress at the end. Change it to any one of the following:
Pervmom 919
Pervmom 919 fucking-away-the-stepmom-stress
Pervmom 919 fucking away the stepmom stress
Pervmom 919/fucking-away-the-stepmom-stress/1
Pervmom 919/fucking-away-the-stepmom-stress/actual-actress

**Comment by d2dyno** [comment]
Hmm, still having sceneid errors

```
2019-07-27 01:39:23,512 (152cabdfe700) :  INFO (__init__:46) - *******MEDIA TITLE****** Pervmom 919
2019-07-27 01:39:23,513 (152cabdfe700) :  INFO (__init__:53) - Getting Search Settings for: Pervmom 919
2019-07-27 01:39:23,513 (152cabdfe700) :  INFO (PAsearchSites:887) - mediaTitle w/ possible abbrieviation: Pervmom 919
2019-07-27 01:39:23,525 (152cabdfe700) :  INFO (PAsearchSites:1063) - mediaTitle w/ possible abbrieviation fixed: Pervmom 919
2019-07-27 01:39:23,529 (152cabdfe700) :  INFO (PAsearchSites:1078) - ^^^^^^^ siteID: 686
2019-07-27 01:39:23,529 (152cabdfe700) :  INFO (PAsearchSites:1080) - ^^^^^^^ Shortening Title
2019-07-27 01:39:23,530 (152cabdfe700) :  INFO (PAsearchSites:1081) - pervmom vs pervmom
2019-07-27 01:39:23,530 (152cabdfe700) :  INFO (PAsearchSites:1084) - 1
2019-07-27 01:39:23,530 (152cabdfe700) :  INFO (PAsearchSites:1133) - 6
2019-07-27 01:39:23,530 (152cabdfe700) :  INFO (PAsearchSites:1133) - searchTitle (before date processing): 919
2019-07-27 01:39:23,531 (152cabdfe700) :  INFO (__init__:63) - Search Title: 919
2019-07-27 01:39:23,531 (152cabdfe700) :  INFO (__init__:72) - 919
2019-07-27 01:39:23,535 (152cabdfe700) :  DEBUG (networking:166) - Requesting 'https://www.pervmom.com/919/1/1/'
2019-07-27 01:39:23,751 (152cabdfe700) :  CRITICAL (agentkit:1014) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': '2019', 'id': '100432', 'name': 'Pervmom 919'} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 790, in search
    results = PAsearchSites.sitePervMom.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/sitePervMom.py", line 12, in search
    titleNoFormatting = searchResult.xpath('//span[@class="p-small red"]')[0].text_content().strip()
UnboundLocalError: local variable 'searchResult' referenced before assignment
```

**Comment by SgtBatten** [comment]
hmm not sure why it says that.

Its literally in the line above it where searchResult is created.
```searchResult = HTML.ElementFromURL(url)
titleNoFormatting = searchResult.xpath('//span[@class="p-small red"]')[0].text_content().strip()```

Might need some deeper checking. unless it was a one off glitch

**Comment by d2dyno** [comment]
Not sure if it resolved itself or it latest change did it, but seems to work now.

**Comment by d2dyno** [comment]
Well, kind of. The result came back, but metadata is getting caught on something

```
2019-07-27 02:26:15,303 (146a0d67d700) :  INFO (__init__:46) - *******MEDIA TITLE****** Pervmom 931
2019-07-27 02:26:15,303 (146a0d67d700) :  INFO (__init__:53) - Getting Search Settings for: Pervmom 931
2019-07-27 02:26:15,303 (146a0d67d700) :  INFO (PAsearchSites:887) - mediaTitle w/ possible abbrieviation: Pervmom 931
2019-07-27 02:26:15,315 (146a0d67d700) :  INFO (PAsearchSites:1063) - mediaTitle w/ possible abbrieviation fixed: Pervmom 931
2019-07-27 02:26:15,319 (146a0d67d700) :  INFO (PAsearchSites:1078) - ^^^^^^^ siteID: 686
2019-07-27 02:26:15,319 (146a0d67d700) :  INFO (PAsearchSites:1080) - ^^^^^^^ Shortening Title
2019-07-27 02:26:15,320 (146a0d67d700) :  INFO (PAsearchSites:1081) - pervmom vs pervmom
2019-07-27 02:26:15,320 (146a0d67d700) :  INFO (PAsearchSites:1084) - 1
2019-07-27 02:26:15,320 (146a0d67d700) :  INFO (PAsearchSites:1133) - 6
2019-07-27 02:26:15,320 (146a0d67d700) :  INFO (PAsearchSites:1133) - searchTitle (before date processing): 931
2019-07-27 02:26:15,320 (146a0d67d700) :  INFO (__init__:63) - Search Title: 931
2019-07-27 02:26:15,321 (146a0d67d700) :  INFO (__init__:72) - 931
2019-07-27 02:26:15,325 (146a0d67d700) :  DEBUG (networking:166) - Requesting 'https://www.pervmom.com/931/1/1/'
2019-07-27 02:26:15,517 (146a0d67d700) :  INFO (sitePervMom:13) - curID: https:__www.pervmom.com_931
2019-07-27 02:26:15,520 (146a0d67d700) :  DEBUG (runtime:88) - Sending packed state data (4636 bytes)
2019-07-27 02:26:15,521 (146a0d67d700) :  DEBUG (runtime:924) - Response: [200] str, 704 bytes
2019-07-27 02:26:32,589 (146a0d67d700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgphYjA0YTFlMzY0ODg1ODZjczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczYwClBlcnZtb20gMTkgMDYgMDEgSXZ5IExlYmVsbGUgRnVja2luZyBBd2F5IHRoZSBTdGVwbW9tIFN0cmVzc3M0Cm5hbWVzMTE0CiUyRm1pc2MlMkZTaXRlcyUyRlBlcnZNb20lMkZwZXJ2bW9tJTJFMTklMkUwNiUyRTAxJTJFaXZ5JTJFbGViZWxsZSUyRWZ1Y2tpbmclMkVhd2F5JTJFdGhlJTJFc3RlcG1vbSUyRXN0cmVzcyUyRW1wNHM4CmZpbGVuYW1lczQwCjgxN2M4MmVkNDA5YThkNTM2M2I2ZWEyY2Q5OGY3ZGJmZTdkMWFlNWJzOApwbGV4SGFzaHM3CjMyOTI0NTlzOApkdXJhdGlvbnM2CjEwMDQzMnMyCmlkcjAK
2019-07-27 02:26:32,590 (146a0d67d700) :  DEBUG (runtime:49) - Received packed state data (4604 bytes)
2019-07-27 02:26:32,593 (146a0d67d700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgphYjA0YTFlMzY0ODg1ODZjczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczYwClBlcnZtb20gMTkgMDYgMDEgSXZ5IExlYmVsbGUgRnVja2luZyBBd2F5IHRoZSBTdGVwbW9tIFN0cmVzc3M0Cm5hbWVzMTE0CiUyRm1pc2MlMkZTaXRlcyUyRlBlcnZNb20lMkZwZXJ2bW9tJTJFMTklMkUwNiUyRTAxJTJFaXZ5JTJFbGViZWxsZSUyRWZ1Y2tpbmclMkVhd2F5JTJFdGhlJTJFc3RlcG1vbSUyRXN0cmVzcyUyRW1wNHM4CmZpbGVuYW1lczQwCjgxN2M4MmVkNDA5YThkNTM2M2I2ZWEyY2Q5OGY3ZGJmZTdkMWFlNWJzOApwbGV4SGFzaHM3CjMyOTI0NTlzOApkdXJhdGlvbnM2CjEwMDQzMnMyCmlkcjAK
2019-07-27 02:26:32,594 (146a0d67d700) :  INFO (agentkit:957) - Searching for matches for {'openSubtitlesHash': 'ab04a1e36488586c', 'name': 'Pervmom 19 06 01 Ivy Lebelle Fucking Away the Stepmom Stress', 'filename': '%2Fmisc%2FSites%2FPervMom%2Fpervmom%2E19%2E06%2E01%2Eivy%2Elebelle%2Efucking%2Eaway%2Ethe%2Estepmom%2Estress%2Emp4', 'plexHash': '817c82ed409a8d5363b6ea2cd98f7dbfe7d1ae5b', 'duration': '3292459', 'id': '100432'}
2019-07-27 02:26:32,594 (146a0d67d700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/100432/tree'
2019-07-27 02:26:32,601 (146a0d67d700) :  INFO (__init__:46) - *******MEDIA TITLE****** Pervmom 19 06 01 Ivy Lebelle Fucking Away the Stepmom Stress
2019-07-27 02:26:32,602 (146a0d67d700) :  INFO (__init__:53) - Getting Search Settings for: Pervmom 19 06 01 Ivy Lebelle Fucking Away the Stepmom Stress
2019-07-27 02:26:32,602 (146a0d67d700) :  INFO (PAsearchSites:887) - mediaTitle w/ possible abbrieviation: Pervmom 19 06 01 Ivy Lebelle Fucking Away the Stepmom Stress
2019-07-27 02:26:32,614 (146a0d67d700) :  INFO (PAsearchSites:1063) - mediaTitle w/ possible abbrieviation fixed: Pervmom 19 06 01 Ivy Lebelle Fucking Away the Stepmom Stress
2019-07-27 02:26:32,617 (146a0d67d700) :  INFO (PAsearchSites:1078) - ^^^^^^^ siteID: 686
2019-07-27 02:26:32,618 (146a0d67d700) :  INFO (PAsearchSites:1080) - ^^^^^^^ Shortening Title
2019-07-27 02:26:32,618 (146a0d67d700) :  INFO (PAsearchSites:1081) - pervmom vs pervmom
2019-07-27 02:26:32,618 (146a0d67d700) :  INFO (PAsearchSites:1084) - 1
2019-07-27 02:26:32,619 (146a0d67d700) :  INFO (PAsearchSites:1133) - 6
2019-07-27 02:26:32,619 (146a0d67d700) :  INFO (PAsearchSites:1133) - searchTitle (before date processing): 19 06 01 Ivy Lebelle Fucking Away the Stepmom Stress
2019-07-27 02:26:32,619 (146a0d67d700) :  INFO (__init__:63) - Search Title: Ivy Lebelle Fucking Away the Stepmom Stress
2019-07-27 02:26:32,619 (146a0d67d700) :  INFO (__init__:67) - Search Date: 2019-06-01
2019-07-27 02:26:32,620 (146a0d67d700) :  INFO (__init__:72) - Ivy%20Lebelle%20Fucking%20Away%20the%20Stepmom%20Stress
2019-07-27 02:26:32,623 (146a0d67d700) :  INFO (sitePervMom:19) - searchTitle.replace: Ivy-Lebelle-Fucking-Away-the-Stepmom-Stress
2019-07-27 02:26:32,624 (146a0d67d700) :  DEBUG (networking:166) - Requesting 'https://www.pervmom.com/Ivy-Lebelle-Fucking-Away-the-Stepmom-Stress'
2019-07-27 02:26:32,964 (146a0d67d700) :  CRITICAL (agentkit:1014) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'openSubtitlesHash': 'ab04a1e36488586c', 'name': 'Pervmom 19 06 01 Ivy Lebelle Fucking Away the Stepmom Stress', 'filename': '%2Fmisc%2FSites%2FPervMom%2Fpervmom%2E19%2E06%2E01%2Eivy%2Elebelle%2Efucking%2Eaway%2Ethe%2Estepmom%2Estress%2Emp4', 'plexHash': '817c82ed409a8d5363b6ea2cd98f7dbfe7d1ae5b', 'duration': '3292459', 'id': '100432'} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 790, in search
    results = PAsearchSites.sitePervMom.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/sitePervMom.py", line 21, in search
    titleNoFormatting = searchResult.xpath('//span[@class="p-small red"]')[0].text_content().strip()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-359b06978/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
```

**Comment by SgtBatten** [comment]
I didn't do anything except delete a blank line in that last one.

That latest one won't match as there is no date match. Needs to be sceneid or exact url

**Comment by d2dyno** [comment]
Sorry, I don't follow? The logs above only used this in the manual match field of Plex: `Pervmom 931`. It's something the agent does to produce `Pervmom 19 06 01 Ivy Lebelle Fucking Away the Stepmom Stress`

**Comment by SgtBatten** [comment]
Ohh you were referring to the first match.

The code above has two different matches going on. One that worked and one that did not. Different files.

But i see it is not doing more for the first one. WIll look into it tomorrow

**Comment by SgtBatten** [comment]
@d2dyno sorry for so many attempts. was doing it from my phone the last few days. Finally home to test it myself. Found the issue and have pushed a fix.

**Comment by d2dyno** [comment]
All good! I was testing from my phone too, I know the struggle :p

Give me a few to test latest change when I get to my laptop.

**Comment by d2dyno** [comment]
Yes, this works fine with sceneid now, thanks!

**Pull request merged**
