### PR TITLE
Use AdultEmpire site for DVD split scenes

### PR DESCRIPTION
**Pull request by extant-squash**
Use AdultEmpire for split scenes from DVDs.
File's with name "Scene x" in filename will use [siteAdultEmpire](https://github.com/PAhelper/PhoenixAdult.bundle/blob/a0a0e534cafc23573548da1f5ed9cac60fffc67e/Contents/Code/siteAdultEmpire.py)

Once the scene matching the specified title exactly and scene number is found, it will stop searching to speed things up.

### CODE REVIEW

**Comment by DirtyRacer1337** [comment]
What if it not `AdultEmpire`?
Random example https://www.digitalplayground.com/scene/4157221/city-of-vices-scene-1

**Comment by extant-squash** [comment]
Think that should fix it. Check's for matches like normal, if no provider found then checks for "Scene x" and uses AdultEmpire

**Comment by extant-squash** [comment]
Double checked that everything works. Looks to be fine for me

**Comment by DirtyRacer1337** [comment]
Now if I store files like `DigitalPlayground/City of Vices - Scene 1` it's doesn't work

What's you trying to do?

**Comment by extant-squash** [comment]
Just tried it and it looks llike it's working

**Comment by DirtyRacer1337** [comment]
No it doesn't

**Comment by extant-squash** [comment]
Think that should do it, forgot about checking the parent folder name. Just moved my code the bottom so it only looks if nothing else works

**Pull request closed without merging**
