### PR TITLE
TeamSkeet API support

### LINKED ISSUE #626: Dadcrush issues
Title is being set simply as ` [TeamSkeet/DadCrush] 2020-02-02`, scene description screens don't seem to be working either. Scene for example: https://www.dadcrush.com/movies/cabin-in-the-woods-cooch

```
2020-02-12 04:19:51,785 (1462d6a77700) :  INFO (__init__:44) - *******MEDIA TITLE****** Dadcrush 20 02 02 Emma Hix Cabin in the Woods Cooch
2020-02-12 04:19:51,785 (1462d6a77700) :  INFO (__init__:51) - Getting Search Settings for: Dadcrush 20 02 02 Emma Hix Cabin in the Woods Cooch
2020-02-12 04:19:51,785 (1462d6a77700) :  INFO (PAsearchSites:1026) - mediaTitle w/ possible abbreviation: Dadcrush 20 02 02 Emma Hix Cabin in the Woods Cooch
2020-02-12 04:19:51,795 (1462d6a77700) :  INFO (PAsearchSites:1226) - mediaTitle w/ possible abbrieviation fixed: Dadcrush 20 02 02 Emma Hix Cabin in the Woods Cooch
2020-02-12 04:19:51,798 (1462d6a77700) :  INFO (PAsearchSites:980) - Site found with method #3
2020-02-12 04:19:51,798 (1462d6a77700) :  INFO (PAsearchSites:1241) - ^^^^^^^ siteID: 748
2020-02-12 04:19:51,798 (1462d6a77700) :  INFO (PAsearchSites:1243) - ^^^^^^^ Shortening Title
2020-02-12 04:19:51,798 (1462d6a77700) :  INFO (PAsearchSites:1244) - dadcrush vs dadcrush
2020-02-12 04:19:51,798 (1462d6a77700) :  INFO (PAsearchSites:1248) - 1
2020-02-12 04:19:51,799 (1462d6a77700) :  INFO (PAsearchSites:1308) - 8
2020-02-12 04:19:51,799 (1462d6a77700) :  INFO (PAsearchSites:1308) - searchTitle (before date processing): 20 02 02 Emma Hix Cabin in the Woods Cooch
2020-02-12 04:19:51,799 (1462d6a77700) :  INFO (__init__:61) - Search Title: Emma Hix Cabin in the Woods Cooch
2020-02-12 04:19:51,799 (1462d6a77700) :  INFO (__init__:65) - Search Date: 2020-02-02
2020-02-12 04:19:51,799 (1462d6a77700) :  INFO (__init__:70) - Emma%20Hix%20Cabin%20in%20the%20Woods%20Cooch
2020-02-12 04:19:51,803 (1462d6a77700) :  INFO (siteDadCrush:9) - searchString: emma-hix-cabin-in-the-woods-cooch
2020-02-12 04:19:51,805 (1462d6a77700) :  DEBUG (networking:138) - Fetching 'https://www.dadcrush.com/movies/emma-hix-cabin-in-the-woods-cooch' from the HTTP cache
2020-02-12 04:19:51,810 (1462d6a77700) :  DEBUG (runtime:88) - Sending packed state data (620 bytes)
2020-02-12 04:19:51,810 (1462d6a77700) :  DEBUG (runtime:924) - Response: [200] str, 756 bytes
```

### LINKED ISSUE #635: SisLovesMe stopped working
Appears that the site no longer pulls data from sceneID either.

```
2020-02-21 17:26:10,279 (1668) :  DEBUG (runtime:88) - Sending packed state data (620 bytes)
2020-02-21 17:26:10,279 (1668) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
2020-02-21 17:26:30,533 (2128) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0CjQ3NDBzMgppZHMxNgpTaXNsb3Zlc21lIC0gMjYxczQKbmFtZW5zNAp5ZWFycjAK
2020-02-21 17:26:30,535 (2128) :  DEBUG (runtime:49) - Received packed state data (588 bytes)
2020-02-21 17:26:30,535 (2128) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0CjQ3NDBzMgppZHMxNgpTaXNsb3Zlc21lIC0gMjYxczQKbmFtZW5zNAp5ZWFycjAK
2020-02-21 17:26:30,536 (2128) :  INFO (agentkit:957) - Searching for matches for {'year': None, 'id': '4740', 'name': 'Sislovesme - 261'}
2020-02-21 17:26:30,536 (2128) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/4740/tree'
2020-02-21 17:26:30,539 (2128) :  INFO (logkit:16) - *******MEDIA TITLE****** Sislovesme - 261
2020-02-21 17:26:30,539 (2128) :  INFO (logkit:16) - Getting Search Settings for: Sislovesme - 261
2020-02-21 17:26:30,540 (2128) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Sislovesme 261
2020-02-21 17:26:30,546 (2128) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Sislovesme 261
2020-02-21 17:26:30,548 (2128) :  INFO (logkit:16) - Site found with method #3
2020-02-21 17:26:30,548 (2128) :  INFO (logkit:16) - ^^^^^^^ siteID: 567
2020-02-21 17:26:30,548 (2128) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-02-21 17:26:30,548 (2128) :  INFO (logkit:16) - sislovesme 2 vs sis loves me
2020-02-21 17:26:30,549 (2128) :  INFO (logkit:16) - 3
2020-02-21 17:26:30,549 (2128) :  INFO (logkit:16) - 8
2020-02-21 17:26:30,549 (2128) :  INFO (logkit:16) - searchTitle (before date processing): 261
2020-02-21 17:26:30,549 (2128) :  INFO (logkit:16) - Search Title: 261
2020-02-21 17:26:30,549 (2128) :  INFO (logkit:16) - 261
2020-02-21 17:26:30,549 (2128) :  INFO (logkit:16) - SceneID: 261
2020-02-21 17:26:30,551 (2128) :  INFO (logkit:16) - Scene Title: 
2020-02-21 17:26:30,551 (2128) :  INFO (logkit:16) - Try Default URL
2020-02-21 17:26:30,558 (2128) :  DEBUG (networking:143) - Requesting 'https://www.sislovesme.com/t2/?single=261'
2020-02-21 17:26:32,115 (2128) :  INFO (logkit:16) - Try Alternate URL
2020-02-21 17:26:32,125 (2128) :  DEBUG (networking:143) - Requesting 'https://www.sislovesme.com/261/banner/1'
2020-02-21 17:26:33,019 (2128) :  CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': None, 'id': '4740', 'name': 'Sislovesme - 261'} (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-97add474d\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 649, in search
    results = PAsearchSites.siteSisLovesMe.search(results, encodedTitle, title, searchTitle, siteNum, lang, searchByDateActor, searchDate, searchSiteID)
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\siteSisLovesMe.py", line 21, in search
    titleNoFormatting = searchResult.xpath('//div[@class="red_big"]/text()')[0].strip()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-97add474d\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
```

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4238474/com.plexapp.agents.phoenixadult.log)

### PR DESCRIPTION
**Pull request by DirtyRacer1337**
Fixes #635, Fixes #626  

Supported sites:
- SisLovesMe
- DadCrush
- DaughterSwap
- BFFs
- FosterTapes
- FamilyStrokes
- PervMom
- Shoplyfter
- ShoplyfterMylf
- ExxxtraSmall
- Little Asians
- Teen JOI
- Black Valley Girls
- Thickumz
- Dyked
- Teens Love Black Cocks

### CODE REVIEW

**Comment by HWatBobby** [comment]
You may be able to add support for BFFs and FosterTapes, too, and FamilyStrokes and PervMom could likely be updated for this. Looks like they all are using the same API.

**Comment by d2dyno** [comment]
What are we waiting on to merge this? @claygoldfinch

**Comment by HWatBobby** [comment]
It looks like a few more sites could be added to this. Shoplyfter, ShoplyfterMylf, Dyked, ExxxtraSmall, Little Asians, Teens Love Black Cocks, Teen JOI, Black Valley Girls, and Thickumz all use the same API as the other sites included in this PR. I believe that would end up being all of the TeamSkeet sites using that API. All others would be included with the other TeamSkeet file.

**Comment by d2dyno** [comment]
@PAhelper or @claygoldfinch can someone review this PRs and merge them?

**Comment by m0uthless** [comment]
hi @DirtyRacer1337 i tried your brench sislovesme for teamskeet content and some time works some time no, can i share with u my log files? thx

```
2020-03-12 16:49:40,535 (2484) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-03-12 16:49:40,536 (2484) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
2020-03-12 16:50:19,788 (22b8) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0Cjc5NzhzMgppZHMxNwpCZmZzIENvbG9yIE1lIEJhZHM0Cm5hbWVuczQKeWVhcnIwCg__
2020-03-12 16:50:19,789 (22b8) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2020-03-12 16:50:19,790 (22b8) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0Cjc5NzhzMgppZHMxNwpCZmZzIENvbG9yIE1lIEJhZHM0Cm5hbWVuczQKeWVhcnIwCg__
2020-03-12 16:50:19,790 (22b8) :  INFO (agentkit:957) - Searching for matches for {'year': None, 'id': '7978', 'name': 'Bffs Color Me Bad'}
2020-03-12 16:50:19,792 (22b8) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/7978/tree'
2020-03-12 16:50:19,806 (22b8) :  INFO (logkit:16) - *******MEDIA TITLE****** Bffs Color Me Bad
2020-03-12 16:50:19,806 (22b8) :  INFO (logkit:16) - Getting Search Settings for: Bffs Color Me Bad
2020-03-12 16:50:19,806 (22b8) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Bffs Color Me Bad
2020-03-12 16:50:19,818 (22b8) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Bffs Color Me Bad
2020-03-12 16:50:19,821 (22b8) :  INFO (logkit:16) - Site found with method #3
2020-03-12 16:50:19,822 (22b8) :  INFO (logkit:16) - ^^^^^^^ siteID: 845
2020-03-12 16:50:19,822 (22b8) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-03-12 16:50:19,822 (22b8) :  INFO (logkit:16) - bffs vs bffs
2020-03-12 16:50:19,822 (22b8) :  INFO (logkit:16) - 1
2020-03-12 16:50:19,822 (22b8) :  INFO (logkit:16) - 8
2020-03-12 16:50:19,822 (22b8) :  INFO (logkit:16) - searchTitle (before date processing): Color Me Bad
2020-03-12 16:50:19,822 (22b8) :  INFO (logkit:16) - Search Title: Color Me Bad
2020-03-12 16:50:19,822 (22b8) :  INFO (logkit:16) - Color%20Me%20Bad
2020-03-12 16:50:23,707 (22b8) :  CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': None, 'id': '7978', 'name': 'Bffs Color Me Bad'} (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-77cb9455c\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "C:\Users\Logan\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 383, in search
    results = PAsearchSites.networkTeamSkeetOther.search(results, encodedTitle, title, searchTitle, siteNum, lang, searchByDateActor, searchDate, searchSiteID)
  File "C:\Users\Logan\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkTeamSkeetOther.py", line 32, in search
    detailsPageElements = getDataFromAPI('%s/moviesContent/%s.json' % (PAsearchSites.getSearchSearchURL(siteNum), sceneName))
  File "C:\Users\Logan\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkTeamSkeetOther.py", line 8, in getDataFromAPI
    data = urllib.urlopen(url).read()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request

2020-03-12 16:50:23,710 (22b8) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-03-12 16:50:23,710 (22b8) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes

```

**Comment by m0uthless** [comment]
thx @DirtyRacer1337 now works well with sislovesme, familystroke, daughterswap, exxxtrasmall and shoplyfter. 
Not working with Dadcrush, no results.
```
2020-03-15 02:27:38,680 (930) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo3MDAxNGQxODY3Mzc0NTgzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczY3CkRhZGNydXNoIDE5IDA2IDE2IEJyb29rbHluIEdyYXkgUGhvbmUgVGFwcGluZyBUaGF0IFN0ZXBkYXVnaHRlciBBc3NzNApuYW1lczEzNApaJTNBJTVDY2xpcHN4eHglNUN0ZWFtc2tlZXQlNUNkYWRjcnVzaCU1Q2RhZGNydXNoJTJFMTklMkUwNiUyRTE2JTJFYnJvb2tseW4lMkVncmF5JTJFcGhvbmUlMkV0YXBwaW5nJTJFdGhhdCUyRXN0ZXBkYXVnaHRlciUyRWFzcyUyRW1wNHM4CmZpbGVuYW1lczQwCjE1MzhjMDk4MjU5ZGY5ZDAzOGI1YjM4M2QwNzQ1NWU3OTMwNmI3NWVzOApwbGV4SGFzaHM3CjMzODI4OTFzOApkdXJhdGlvbnM0Cjc3NTZzMgppZHIwCg__
2020-03-15 02:27:38,683 (930) :  DEBUG (runtime:49) - Received packed state data (6216 bytes)
2020-03-15 02:27:38,684 (930) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo3MDAxNGQxODY3Mzc0NTgzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczY3CkRhZGNydXNoIDE5IDA2IDE2IEJyb29rbHluIEdyYXkgUGhvbmUgVGFwcGluZyBUaGF0IFN0ZXBkYXVnaHRlciBBc3NzNApuYW1lczEzNApaJTNBJTVDY2xpcHN4eHglNUN0ZWFtc2tlZXQlNUNkYWRjcnVzaCU1Q2RhZGNydXNoJTJFMTklMkUwNiUyRTE2JTJFYnJvb2tseW4lMkVncmF5JTJFcGhvbmUlMkV0YXBwaW5nJTJFdGhhdCUyRXN0ZXBkYXVnaHRlciUyRWFzcyUyRW1wNHM4CmZpbGVuYW1lczQwCjE1MzhjMDk4MjU5ZGY5ZDAzOGI1YjM4M2QwNzQ1NWU3OTMwNmI3NWVzOApwbGV4SGFzaHM3CjMzODI4OTFzOApkdXJhdGlvbnM0Cjc3NTZzMgppZHIwCg__
2020-03-15 02:27:38,684 (930) :  INFO (agentkit:957) - Searching for matches for {'openSubtitlesHash': '70014d1867374583', 'name': 'Dadcrush 19 06 16 Brooklyn Gray Phone Tapping That Stepdaughter Ass', 'filename': 'Z%3A%5Cclipsxxx%5Cteamskeet%5Cdadcrush%5Cdadcrush%2E19%2E06%2E16%2Ebrooklyn%2Egray%2Ephone%2Etapping%2Ethat%2Estepdaughter%2Eass%2Emp4', 'plexHash': '1538c098259df9d038b5b383d07455e79306b75e', 'duration': '3382891', 'id': '7756'}
2020-03-15 02:27:38,687 (930) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/7756/tree'
2020-03-15 02:27:38,701 (930) :  INFO (logkit:16) - *******MEDIA TITLE****** Dadcrush 19 06 16 Brooklyn Gray Phone Tapping That Stepdaughter Ass
2020-03-15 02:27:38,701 (930) :  INFO (logkit:16) - Getting Search Settings for: Dadcrush 19 06 16 Brooklyn Gray Phone Tapping That Stepdaughter Ass
2020-03-15 02:27:38,701 (930) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Dadcrush 19 06 16 Brooklyn Gray Phone Tapping That Stepdaughter Ass
2020-03-15 02:27:38,713 (930) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Dadcrush 19 06 16 Brooklyn Gray Phone Tapping That Stepdaughter Ass
2020-03-15 02:27:38,717 (930) :  INFO (logkit:16) - Site found with method #3
2020-03-15 02:27:38,717 (930) :  INFO (logkit:16) - ^^^^^^^ siteID: 748
2020-03-15 02:27:38,717 (930) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-03-15 02:27:38,719 (930) :  INFO (logkit:16) - dadcrush vs dadcrush
2020-03-15 02:27:38,719 (930) :  INFO (logkit:16) - 1
2020-03-15 02:27:38,719 (930) :  INFO (logkit:16) - 8
2020-03-15 02:27:38,719 (930) :  INFO (logkit:16) - searchTitle (before date processing): 19 06 16 Brooklyn Gray Phone Tapping That Stepdaughter Ass
2020-03-15 02:27:38,720 (930) :  INFO (logkit:16) - Search Title: Brooklyn Gray Phone Tapping That Stepdaughter Ass
2020-03-15 02:27:38,720 (930) :  INFO (logkit:16) - Search Date: 2019-06-16
2020-03-15 02:27:38,720 (930) :  INFO (logkit:16) - Brooklyn%20Gray%20Phone%20Tapping%20That%20Stepdaughter%20Ass
2020-03-15 02:27:38,727 (930) :  DEBUG (runtime:88) - Sending packed state data (6248 bytes)
2020-03-15 02:27:38,727 (930) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
```

There's a possibility to add She's New and Bad Milfs? 

I need to open an inssue if this pull is merged?

Thx!

**Pull request merged**
