### PR TITLE
API support for lots of sites

### PR DESCRIPTION
**Pull request by DirtyRacer1337**
Supported sites:
- Girlfriends Films
- 21Naturals
- Pure Taboo
- Immoral Live
- 21Sextury
- Anal Teen Angels
- Deepthroat Frenzy
- DP Fanatics
- Footsie Babes
- Gapeland
- Lez Cuties
- Pix and Video
- 21FootArt
- 21EroticAnal
- Burning Angel
- Devils Film
- Rocco Siffredi
- 21Sextreme
- LustyGrandmas
- GrandpasFuckTeens
- TeachMeFisting
- Zoliboy
- DominatedGirls
- Asshole Fever
- Butt Plays

Doesn't have API Key on page:
- HardX
- EroticaX
- DarkX
- LesbianX
- Throated
- Nuru Massage
- Mommy Blows Best
- Only Teen Blowjobs
- 1000 Facials
- Immoral Live
- Fantasy Massage
- All Girl Massage
- Soapy Massage
- Milking Table
- Massage Parlor
- Tricky Spa
- Pretty Dirty
- Peter North
- Tera Patrick
- Sunny Leone
- Lane Sisters
- Dylan Ryder
- Abbey Brooks
- Devon Lee
- Hanna Hilton
- POV Massage
- AllBlackX

### CODE REVIEW

**Comment by pedrolara-boop** [comment]
Adulttime.com is a website that comes with the girlsway subscription and offers a lot of content from other sites (list below). Unfortunately, the search is locked behind the paywall. But the API seems to be almost the same and would return data for tons of sites. It is even possible to match results using the current non-api code. Like 170225.

21 Bonus (2944)
21 Naturals (969)
21 Sextreme (4478)
21 Sextury (10422)
Adam and Eve Pictures (26)
Adult Time Films (32)
Adult Time Originals (129)
Alt Erotic (29)
Analized (55)
Anatomik Media (25)
Archangel Video (25)
Bare Maidens (20)
Black Label Mag (22)
Burning Angel (1520)
Club Seventeen (22)
Devil's Film (7140)
Evil Angel Films (5)
Exxxtra Small (7)
Fame Digital (10386)
Fantasy Massage (2143)
Femjoy (41)
Filthy Pov (47)
Fister Twister (15)
Fit18 (10)
Girls Out West (9)
Girls Rimming (23)
Girlsway (1773)
HitzeFrei (26)
Holly Randall (55)
Hot Guys Fuck (16)
Jay Rock Films (119)
JoyBear (27)
Joymii (36)
Korina Kova (12)
Lightsouthern Cinema (8)
Love Her Feet (26)
MMP Network (21)
MixedX (22)
My Pervy Family (45)
Pegas Productions (35)
PervCity (44)
Pretty Dirty (206)
Pure Taboo (241)
RealSensual (33)
Rocco Siffredi (2132)
Sinful XXX (43)
Spizoo (104)
Vivid (7052)
Wasteland (58)
Wolf Wagner (16)
XConfessions (13)

Let me know if there is a way for me to share the API data.
Here is the link from the developer window.

https://tsmkfa364q-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(3.35.1)%3B%20Browser%20(lite)%3B%20react%20(16.12.0)%3B%20react-instantsearch%20(5.7.0)%3B%20JS%20Helper%202.26.0&x-algolia-application-id=TSMKFA364Q&x-algolia-api-key=YzM2YWQ5NmQ1NzllNjlkODI3YmJiYTgyZjUyYzM5ODBkZjk4MmY1Nzc2MzQ2OTFiZmM4NmNmNWJiZjcwOGI1YnZhbGlkVW50aWw9MTU4MzM1MTY5MyZyZXN0cmljdEluZGljZXM9YWxsJTJBJmZpbHRlcnM9c2VnbWVudCUzQWFkdWx0dGltZSZ1c2VyVG9rZW49NDIxYTZjNmJiN2I2Zjg0NDkwNTE3MWQ0ZTFkMjcxZjEzMWUxMmQxOWFhYTRlNjgxYWUyYjczZjU3N2Q1OTQyZQ%3D%3D

**Comment by pedrolara-boop** [comment]
Movies would probably be a problem since they don't seem to offer them.
The list that I posted is copied from their website and shows the number of videos of each studio. So far, only the old content from spizoo seems not to be available. 

However, most studios seem to have their full content available. Especially some small ones. 

Let me know if there is any way to help.

**Comment by pedrolara-boop** [comment]
Girlsway loads the studio logo as Poster. 
MommysGirl.20.03.14.DON'T.Bring.Your.Daughter.To.Work.Day
GirlsWay.20.03.12.Jade.Baker.And.Brooke.Haze.A.Friendly.Wager

It also results a lot of unrelated videos.

**Comment by PAhelper** [comment]
When I first started merging your code pulls, this whole API support concept was unfamiliar and scary. I merged one of the pull requests for a smaller site, tested, researched what exactly you're accessing to get the data and now I like the idea of API support; I'm on board.

Unfortunately, I broke the hell out of this pull request because I've merged a bunch of other commits after it. If you can get this put back together, I'll merge it. Sorry for the hassle...

**Comment by DirtyRacer1337** [comment]
It's not ready anyway, still having issues, I'll rewrite it later.

**Pull request closed without merging**
