### PR TITLE
Provide Limited Evil Angel suppot (directURL only)

### PR DESCRIPTION
**Pull request by yakboyslim**
Might be something worth pulling in for now until someone can crack the code on matching with search.

### CODE REVIEW

**Comment by claygoldfinch** [comment]
Just tested, everything working well for me! Upgrading this from DirectURL to SceneID should be pretty easy if you get the chance, as these two links are both valid:
https://www.evilangel.com/en/video/Teen-Kenzie-Gaping-Anal--Cum-Facial/149041
https://www.evilangel.com/en/video/1/149041

**Comment by neon2194** [comment]
Hmm, can't get this working. Suppose i have this scene below: 

https://www.evilangel.com/en/video/Smells-Like-Paris/147559

What's the direct match to get this working in the search tab?

I've tried the url itself and also several combinations of:

evil angel - en - video - Smells-Like-Paris 147559

**Comment by yakboyslim** [comment]
evilangel - /Smells-Like-Paris/147559

**Comment by neon2194** [comment]
> evilangel - /Smells-Like-Paris/147559

Thanks, I tried that but no results

**Comment by chonka1** [comment]
> 
> 
> > evilangel - /Smells-Like-Paris/147559
> 
> Thanks, I tried that but no results

Figured it out.  Remove the first forward slash.

**Comment by neon2194** [comment]
> > > evilangel - /Smells-Like-Paris/147559
> > 
> > 
> > Thanks, I tried that but no results
> 
> Figured it out. Remove the first forward slash.


Thank you that works :)

**Comment by cwilcoxc** [comment]
Finding that this method is no longer working. Anyone else getting anywhere with this?

**Pull request merged**
