### PR TITLE
Switched Lil Humpers url to Reality Kings

### PR DESCRIPTION
**Pull request by WolHloW**
Original site was missing newer scenes that are available on the main Reality Kings site.

### CODE REVIEW

**Comment by DirtyRacer1337** [comment]
It's not about code lines, it's about usage. Better use id range instead adding to every site.
My solution was in using two numbers of siteNum like:
```python
{
    0: {
        0: ('BlackedRaw', 'https://www.blackedraw.com', '/api'),
        1: ('Blacked', 'https://www.blacked.com'),
        2: ('Vixen', 'http://www.vixen.com'),
        3: ('Tushy', 'https://www.tushy.com'),
        4: ('TushyRaw', 'https://www.tushyraw.com'),
        5: ('Deeper', 'https://www.deeper.com'),
    },
}
```
bigger example in https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/blob/master/data/SiteList.json
But it's too much of work

**Comment by WolHloW** [comment]
Hmmm, in that case how about merging the provider and site list into something like this, that way you have no provider ID, but it's not saved anyway

```
searchSiteProviders = {
    networkStrike3: {
        0: ('BlackedRaw', 'https://www.blackedraw.com', '/api'),
        1: ('Blacked', 'https://www.blacked.com', '/api'),
    },
    network1service: {
        2: ('Brazzers', 'http://www.brazzers.com', 'https://site-api.project1service.com'),
    },
}
```

**Comment by WolHloW** [comment]
This branch now only contains the change in url for Lil Humpers. I reverted the merge from provider_rework, as it was never meant to be merged into this branch, but somehow GitHub merged it both ways when I merged this one into provider_rework.

I'll create a new one for the provider rework when I'm done with another version of that.

**Comment by DirtyRacer1337** [comment]
Can you made it in one commit, or I can do it?

You not get idea about sitelist.
I fill it like:
```json
"0": {
  "0": [ "Brazzers", "https://www.brazzers.com", "https://site-api.project1service.com" ],
  "1": [ "Asses In Public" ],
},
"1": {
  "0": [ "Bang", "https://www.bang.com", "https://617fb597b659459bafe6472470d9073a.us-east-1.aws.found.io/videos/video/_search" ],
},
```
instead
```json
"0": [ "Brazzers", "https://www.brazzers.com", "https://site-api.project1service.com" ],
"1": [ "Asses In Public", "https://www.brazzers.com", "https://site-api.project1service.com" ],
"2": [ "Bang", "https://www.bang.com", "https://617fb597b659459bafe6472470d9073a.us-east-1.aws.found.io/videos/video/_search" ],
```

and provide associated with first id
```json
"0": "Network1service",
"1": "NetworkBang",
```

**Comment by WolHloW** [comment]
I took a look at what you did there, but I suggested a variation based on that. It would remove the need for the separate list of providers, and imho it makes it more readable, since you don't have to look up which provider belongs to the provider ID. Unless you want to start saving the provider ID along with the siteNumber, I figured it wasn't needed.

**Comment by DirtyRacer1337** [comment]
> Hmmm, in that case how about merging the provider and site list into something like this, that way you have no provider ID, but it's not saved anyway
> 
> ```
> searchSiteProviders = {
>     networkStrike3: {
>         0: ('BlackedRaw', 'https://www.blackedraw.com', '/api'),
>         1: ('Blacked', 'https://www.blacked.com', '/api'),
>     },
>     network1service: {
>         2: ('Brazzers', 'http://www.brazzers.com', 'https://site-api.project1service.com'),
>     },
> }
> ```

You never know which id will be next, real example after converting
```python
'networkStrike3': {
    0: ('BlackedRaw', 'https://www.blackedraw.com','/api'),
    1: ('Blacked', 'https://www.blacked.com', '/api'),
    52: ('Vixen', 'http://www.vixen.com', '/api'),
    136: ('Tushy', 'https://www.tushy.com', '/api'),
    670: ('TushyRaw', 'https://www.tushyraw.com', '/api'),
    671: ('Deeper', 'https://www.deeper.com', '/api'),
},
```

**Pull request closed without merging**
