### PR TITLE
postprocessing improvements

### PR DESCRIPTION
**Pull request by SgtBatten**
Cleanup argument -c
Cleanup empty folders and delete leftover files such as .txt and .jpg
Rename files in accordance with collections.py
Move files to new location if set in collections.py
Capitalise file names better

### CODE REVIEW

**Comment by SgtBatten** [comment]
Wanted to make a visible comment on how this is progressing. Every new commit i do is fully functional so yes this is WIP but it can be pulled anytime you want and will work.

I have added some really good functionality to this script now.
Up until now scenes that the agent needs a sceneID to match always require manually renaming and searching for said scene IDs
I have found a fairly simple method for including this search and rename automatically.
My workflow is now vastly superior to before and entirely automated for these sites now.
As of this comment i have only done 3 sites:
DaneJones - my downloads always just have the actress name, automatically replaced with the scene title now (e.g DaneJones - title (date).mp4)
Nubiles Network - Automatically find and input the sceneID into the filename (e.g PrincessCum - 12345 - title (date).mp4)
BrattySis - same as nubiles

This only works for recently released scenes. To keep things reasonably speedy I am only searching the latest releases type pages on each site for matches (mainly by date match)

In theory you could include multiple pages of each of these sites to automate the match. I put an example of this in the nubiles section of siteOverrides.py

**Comment by SgtBatten** [comment]
Some context for people reading along. This

The original file downloaded in sabnzbd was `e80f3ec0fa9335c4bf04ca0b95b12a8`

1. The script looks at the folder name to determine is it is usable. If it is it determines the date, the studio and the title.
2. It trims excess junk from the end and capitalises makes the title look nice
3. It checks if the user has specified any studio specific directory or capitalisation
4. It checks if there is any renaming required to get a plex match (supported sites only)
5. It moves and renames the file according to your specifications.
6. It deletes leftover files and removes the old folder.


```INFO:pa_renamer:Starting to process: P:\Plex\Videos\Porn\New\Passionhd 19 07 17 kiara cole sneaky stepdaughter XXX 1080p MP4-KTR-Pornfuscated
INFO:patools:The Dir is: P:\Plex\Videos\Porn\New\Passionhd 19 07 17 kiara cole sneaky stepdaughter XXX 1080p MP4-KTR-Pornfuscated
DEBUG:patools:Date string determined to be: 2019-07-17
DEBUG:pa_renamer:Full shoot dict:
DEBUG:pa_renamer:{'date': '2019-07-17', 'studio': 'Passionhd', 'filename_title': 'kiara cole sneaky stepdaughter'}
DEBUG:pa_renamer: Before overrides the name is : Passionhd - Kiara Cole Sneaky Stepdaughter (2019-07-17).mp4
DEBUG:siteOverrides: Before:
DEBUG:siteOverrides:    Site: Passionhd
DEBUG:siteOverrides:    Dir: P:\Plex\Videos\Porn\New\Passionhd 19 07 17 kiara cole sneaky stepdaughter XXX 1080p MP4-KTR-Pornfuscated
DEBUG:siteOverrides:    Title: kiara cole sneaky stepdaughter
DEBUG:siteOverrides:    Date: 2019-07-17
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): passion-hd.com
DEBUG:urllib3.connectionpool:https://passion-hd.com:443 "GET /?page=1 HTTP/1.1" 200 10247
DEBUG:pa_renamer: The filetype is: mp4
DEBUG:pa_renamer: Atempting to gather Media Info
DEBUG:siteOverrides: Resolution: 1080p, Framerate: 23.976
DEBUG:pa_renamer: After:
DEBUG:pa_renamer:    New directory: P:\Plex\Videos\Travis\Porn\New\Passion HD 1080p 23.976fps
DEBUG:pa_renamer:    New file name: PassionHD - Sneaky Stepdaughter (2019-07-17).mp4
INFO:pa_renamer: Renaming/Moving from: P:\Plex\Videos\Porn\New\Passionhd 19 07 17 kiara cole sneaky stepdaughter XXX 1080p MP4-KTR-Pornfuscated\PassionHD - Sneaky Stepdaughter (2019-07-17).mp4 --> P:\Plex\Videos\Porn\New\Passion HD 1080p 23.976fps\PassionHD - Sneaky Stepdaughter (2019-07-17).mp4
INFO:pa_renamer: Empty Directory Deleted
INFO:pa_renamer: Successful```

**Comment by kamuk90** [comment]
thx a lot!
expect on linux?

**Comment by SgtBatten** [comment]
> thx a lot!
> expect on linux?

#298 Ill give it a crack. you'll need to test it once i convert from windows.

**Pull request merged**
