### PR TITLE
CherryPimps Updates

### PR DESCRIPTION
**Pull request by HWatBobby**
Changed the sites previously associated with Pimp.XXX, renamed Family.XXX to Taboo (new name on CherryPimps), added Busted, Cheese.XXX, Femme, & Fresh

### CODE REVIEW

**Comment by HWatBobby** [comment]
Having an issue with some of the searching. Some of the scene titles require an apostrophe ('), but the search keeps removing the apostrophe and make it a space that gets replaced with a +. This makes it so those scenes aren't found. Unsure of how to fix that so the search includes the apostrophes.

Ex. Taboo - 2017-11-16 - Alex's True Skills Revealed [Alex Harper].mp4
It searches for this:
 https://cherrypimps.com/search.php?query=Alex+s+True+Skills+Revealed

when it should search for this:
https://cherrypimps.com/search.php?query=Alex%27s+True+Skills+Revealed

**Comment by DirtyRacer1337** [comment]
@HWatBobby You can avoid the words with apostrophe,
https://cherrypimps.com/search.php?query=True+Skills+Revealed
or use code somethinkg like that
```python
def generateEncodedTitle(searchTitle):
    newSearchTitle = ''

    for word in searchTitle.split():
        if word == 's':
            newSearchTitle += '%%27%s' % word
        elif word:
            newSearchTitle += ' %s' % word

    newSearchTitle = newSearchTitle.strip().replace(' ', '+')

    return newSearchTitle
```

**Comment by HWatBobby** [comment]
I'm at a loss when it comes to adding that code. Can't seem to figure out where I would place it to get it to properly work. I assume the code you provided goes in the networkCherryPimps file, but I don't understand enough about Python to know where it fits in that file.

**Comment by DirtyRacer1337** [comment]
@HWatBobby I added it in eea5c60aa830b1bef93078fbd0b7ee96b5f8e8bb

**Comment by HWatBobby** [comment]
@DirtyRacer1337

Reverted back to Family.XXX and added Taboo separately. It all looks to be working now, with the exception of the actor picture pulls. It is pulling the same photo for all actors in a scene. Pulls the photo of the actor listed first. I'll mark this as ready since the rest of it looks to be working properly.

**Pull request merged**
