### PR TITLE
Better Matching with PASearchSites

### PR DESCRIPTION
**Pull request by SgtBatten**

### CODE REVIEW

**Comment by claygoldfinch** [comment]
Why don't we just add "Lets Try Anal" as a shortname? Additionally, we can do this for other sites with apostrophes in the name - such as "Don't Break Me".

**Comment by SgtBatten** [comment]
Mm I didn't think of that. I'll amend it today. Nice!

**Comment by SgtBatten** [comment]
Actually it seems this whole request is unecessary.

the code already strips apostrophes out

```if searchFilter.lower().replace(".com","").replace("'","").split(' ', 1)[0] == sites[0].lower().replace(" ","").replace("'",""):```

**Comment by SgtBatten** [comment]
But now i've found the issue is actually in the stripping of the site from the media title

```searchTitle = mediaTitle[len(searchSites[searchSiteID][0].replace(" ",""))+1:]```

If searchSiteID][0] contains an apostrophe and the file name does not it ends up stripping one character too many.

So we could resolve it by doing the shortnames as originally suggested by @claygoldfinch But this requires future shortnames to be added if new sites are added. Similarly my original solution also has the same issue.

Im thinking this could be solved by changing the code to 

```searchTitle = mediaTitle[len(searchSites[searchSiteID][0].replace(" ","")):].strip()```
which in theory works provided there is only one apostrophe at most. If there is not one then the strip() function would remove the leading space which would be left in the searchTitle.

**Comment by SgtBatten** [comment]
Okay heres what I came up with:

```Log(mediaTitle[:len(searchSites[searchSiteID][0])].lower() + " vs " + searchSites[searchSiteID][0].lower())
        # searchSites [0] matches madiaTitle
        if mediaTitle[:len(searchSites[searchSiteID][0])].lower() == searchSites[searchSiteID][0].lower():
            searchTitle = mediaTitle[len(searchSites[searchSiteID][0])+1:]
            Log("1")
        # searchSites [0] contains an ' but mediaTitle does not
        elif mediaTitle[:len(searchSites[searchSiteID][0].replace("'",""))].lower() == searchSites[searchSiteID][0].lower().replace("'",""):
            searchTitle = mediaTitle[len(searchSites[searchSiteID][0]):]
            Log("2")
        # searchSites [0] contains an ' and spaces but mediaTitle does not
        elif mediaTitle[:len(searchSites[searchSiteID][0].replace(" ","").replace("'",""))].lower() == searchSites[searchSiteID][0].lower().replace(" ","").replace("'",""):
            searchTitle = mediaTitle[len(searchSites[searchSiteID][0].replace(" ","").replace("'",""))+1:]
            Log("3")
        # searchSites [0] and mediaTitle have the same punctuation but differnt spaces
        elif mediaTitle[:len(searchSites[searchSiteID][0].replace(" ",""))].lower() == searchSites[searchSiteID][0].lower().replace(" ",""):
            searchTitle = mediaTitle[len(searchSites[searchSiteID][0].replace(" ",""))+1:]
            Log("4")
        else:
            searchTitle = mediaTitle
            Log("5")
        if searchTitle[:4].lower() == "com ":
            searchTitle = searchTitle[4:]
            Log("6")
        Log("7")```
Let's try anal 4352240/tight-and-horny
matches with 1
Lets try anal 4352240/tight-and-horny
matches with 2
Letstryanal 4352240/tight-and-horny
matches with 3
Let'stryanal 4352240/tight-and-horny
matches with 4

Can you see issues with anything here?

**Comment by SgtBatten** [comment]
I have been using this code for several days now. No issues with my subset of sites.

@claygoldfinch I didn't want to commit it without other people testing

**Comment by d2dyno** [comment]
Tested on Letstryanal, Babes, and newsensations and never had an issue caused by these changes :smiley:

**Pull request merged**
