### PR TITLE
added option to switch Language for MyDirtyHobby

### PR DESCRIPTION
**Pull request by HA2278**
Added option to switch Language for MyDirtyHobby, by using MyDirtyHobbyDE as site name, as the site is mainly a german site (and the scenes I was trying to add have german titles).
Since the search on the site only works in english, not in german, I had to use google search again.
Also, searching mydirtyhobby.com on google doesn't work, so I had to use mydirtyhobby.de (which censors titles and descriptions), then simply change the main url.
Thanks for fixing my messy code from before.
I hope this addition is okay!

### CODE REVIEW

**Comment by DirtyRacer1337** [comment]
Try with my solution 3f75cd9a43949fea54d0581078365043de0bf873

You can set language in library settings

**Comment by chempke** [comment]
Is it possible to adopt the language library setting in the metadata. I now have my library settings in german and I can find german titles in the search, but the loaded metadata (title and summary) are in english for almost all scenes that I tested.

**Comment by chempke** [comment]
Search: MyDirtyHobby - CaroCream Heftig Riskant! Cumshot von notgeilem Fußgänger

```
2021-02-10 14:13:43,269 (a4c8) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmRlczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjI1MTc4MHMyCmlkczcyCm15ZGlydHlob2JieSBjYXJvY3JlYW0gSGVmdGlnIFJpc2thbnQhIEN1bXNob3Qgdm9uIG5vdGdlaWxlbSBGdcOfZ8OkbmdlcnM0Cm5hbWVzNAoyMDE3czQKeWVhcnIwCg__
2021-02-10 14:13:43,270 (a4c8) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-02-10 14:13:43,270 (a4c8) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmRlczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjI1MTc4MHMyCmlkczcyCm15ZGlydHlob2JieSBjYXJvY3JlYW0gSGVmdGlnIFJpc2thbnQhIEN1bXNob3Qgdm9uIG5vdGdlaWxlbSBGdcOfZ8OkbmdlcnM0Cm5hbWVzNAoyMDE3czQKeWVhcnIwCg__
2021-02-10 14:13:43,270 (a4c8) :  INFO (agentkit:961) - Searching for matches for {'year': '2017', 'id': '251780', 'name': 'mydirtyhobby carocream Heftig Riskant! Cumshot von notgeilem Fu\xc3\x9fg\xc3\xa4nger'}
2021-02-10 14:13:43,272 (a4c8) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/251780/tree'
2021-02-10 14:13:43,276 (a4c8) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** mydirtyhobby carocream Heftig Riskant! Cumshot von notgeilem Fußgänger
2021-02-10 14:13:43,276 (a4c8) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: mydirtyhobby carocream Heftig Riskant! Cumshot von notgeilem Fußgänger
2021-02-10 14:13:43,282 (a4c8) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: mydirtyhobby carocream Heftig Riskant! Cumshot von notgeilem Fußgänger
2021-02-10 14:13:43,285 (a4c8) :  INFO (logkit:16) - ^^^^^^^ siteNum: 1237
2021-02-10 14:13:43,285 (a4c8) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2021-02-10 14:13:43,286 (a4c8) :  INFO (logkit:16) - Search Title (before date processing): Carocream Heftig Riskant Cumshot Von Notgeilem Fu G Nger
2021-02-10 14:13:43,286 (a4c8) :  INFO (logkit:16) - {'siteName': 'mydirtyhobby', 'searchDate': None, 'siteNum': 1237, 'searchTitle': 'Carocream Heftig Riskant Cumshot Von Notgeilem Fu G Nger'}
2021-02-10 14:13:43,286 (a4c8) :  INFO (logkit:16) - SearchData.title: Carocream Heftig Riskant Cumshot Von Notgeilem Fu G Nger
2021-02-10 14:13:43,286 (a4c8) :  INFO (logkit:16) - Provider: siteMyDirtyHobby
2021-02-10 14:13:43,288 (a4c8) :  INFO (logkit:16) - Requesting GET "https://de.mydirtyhobby.com/search?searchKeyword=Carocream%20Heftig%20Riskant%20Cumshot%20Von%20Notgeilem%20Fu%20G%20Nger"
2021-02-10 14:13:43,556 (a4c8) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-02-10 14:13:43,558 (a4c8) :  DEBUG (runtime:924) - Response: [200] str, 876 bytes
2021-02-10 14:13:46,740 (60bc) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZGVzNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoyNTE3ODBzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM1Ck1vdmllczEwCm1lZGlhX3R5cGVzMTY5CmNvbS5wbGV4YXBwLmFnZW50cy5waG9lbml4YWR1bHQ6Ly8yZ2hjV1QySjJ0MjMxaVo4ZTkzNWRUVXoxZGNTTkY0WFJlMWJmZmZzV21jdHQxeHRQaTJmMnF0QkJrdm5nNHVSczVQc1Y0bVJHdjhFVU15SkduRFZOcktMa1I2bU1uaFR4cTZoc2NlSnFXM2tKc012MlR4Z2JxbzFEQnwxMjM3P2xhbmc9ZGVzNApndWlkczEyNwoyZ2hjV1QySjJ0MjMxaVo4ZTkzNWRUVXoxZGNTTkY0WFJlMWJmZmZzV21jdHQxeHRQaTJmMnF0QkJrdm5nNHVSczVQc1Y0bVJHdjhFVU15SkduRFZOcktMa1I2bU1uaFR4cTZoc2NlSnFXM2tKc012MlR4Z2JxbzFEQnwxMjM3czIKaWRyMAo_
2021-02-10 14:13:46,742 (60bc) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-02-10 14:13:46,742 (60bc) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZGVzNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoyNTE3ODBzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM1Ck1vdmllczEwCm1lZGlhX3R5cGVzMTY5CmNvbS5wbGV4YXBwLmFnZW50cy5waG9lbml4YWR1bHQ6Ly8yZ2hjV1QySjJ0MjMxaVo4ZTkzNWRUVXoxZGNTTkY0WFJlMWJmZmZzV21jdHQxeHRQaTJmMnF0QkJrdm5nNHVSczVQc1Y0bVJHdjhFVU15SkduRFZOcktMa1I2bU1uaFR4cTZoc2NlSnFXM2tKc012MlR4Z2JxbzFEQnwxMjM3P2xhbmc9ZGVzNApndWlkczEyNwoyZ2hjV1QySjJ0MjMxaVo4ZTkzNWRUVXoxZGNTTkY0WFJlMWJmZmZzV21jdHQxeHRQaTJmMnF0QkJrdm5nNHVSczVQc1Y0bVJHdjhFVU15SkduRFZOcktMa1I2bU1uaFR4cTZoc2NlSnFXM2tKc012MlR4Z2JxbzFEQnwxMjM3czIKaWRyMAo_
2021-02-10 14:13:46,743 (60bc) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.phoenixadult://2ghcWT2J2t231iZ8e935dTUz1dcSNF4XRe1bfffsWmctt1xtPi2f2qtBBkvng4uRs5PsV4mRGv8EUMyJGnDVNrKLkR6mMnhTxq6hsceJqW3kJsMv2Txgbqo1DB|1237?lang=de
2021-02-10 14:13:46,743 (60bc) :  DEBUG (model:234) - Deserializing from C:\Users\dzemk\AppData\Local\Plex Media Server\Metadata\Movies\2\a8aebcdd8ef75b3c7751e3865ede4c9fcc0324f.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2021-02-10 14:13:46,749 (60bc) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/251780/tree'
2021-02-10 14:13:46,755 (60bc) :  INFO (logkit:16) - ******UPDATE CALLED*******
2021-02-10 14:13:46,755 (60bc) :  INFO (logkit:16) - SiteNum: 1237
2021-02-10 14:13:46,756 (60bc) :  INFO (logkit:16) - Provider: siteMyDirtyHobby
2021-02-10 14:13:46,756 (60bc) :  INFO (logkit:16) - Requesting GET "https://de.mydirtyhobby.com/profil/9756061-CaroCream/videos/3542131-Heftig-Riskant-Cumshot-von-notgeilem-Fussgaenger"
2021-02-10 14:13:47,351 (60bc) :  INFO (logkit:16) - Artwork found: 1
2021-02-10 14:13:47,352 (60bc) :  INFO (logkit:16) - Requesting GET "https://cdn1-s-ha-e17t.mdhcdn.com/MURB-7FtipBR3YBC/d/u/tmp/img/user/hashed/videos/1/6/0/9756061/5755d615a8cf6_sc_orig.jpg?validfrom=1610802827&validto=1615122827&hash=gbkQ5PdVMQEEA19CcsEZSyJxvM8%3D"
2021-02-10 14:13:47,509 (60bc) :  INFO (logkit:16) - Genres
2021-02-10 14:13:47,509 (60bc) :  INFO (logkit:16) - Actors
2021-02-10 14:13:47,512 (60bc) :  INFO (logkit:16) - Requesting HEAD "https://cdn1-s-ha-e17t.mdhcdn.com/B6RM_Q99FV_RlVbRVEQU6AQU6Ah/d/u/tmp/img/user/hashed/orig/1/6/0/9756061/9756061_softprofil.jpg?validfrom=1610802827&validto=1615122827&hash=Z9d3VFlp6946Tspp2qX%2FUPTG5n4%3D"
2021-02-10 14:13:47,585 (60bc) :  INFO (logkit:16) - Actor: Carocream https://cdn1-s-ha-e17t.mdhcdn.com/B6RM_Q99FV_RlVbRVEQU6AQU6Ah/d/u/tmp/img/user/hashed/orig/1/6/0/9756061/9756061_softprofil.jpg?validfrom=1610802827&validto=1615122827&hash=Z9d3VFlp6946Tspp2qX%2FUPTG5n4%3D
2021-02-10 14:13:47,619 (60bc) :  DEBUG (model:229) - Serializing to C:\Users\dzemk\AppData\Local\Plex Media Server\Metadata\Movies\2\a8aebcdd8ef75b3c7751e3865ede4c9fcc0324f.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2021-02-10 14:13:47,621 (60bc) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-02-10 14:13:47,621 (60bc) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes

```

Result after matching: Fierce Risky! Cumshot of notgeilem pedestrian

**Comment by DirtyRacer1337** [comment]
@chempke This should help cd814e447d9f95e687c69a46b42f497055f72695

**Comment by chempke** [comment]
Thanks, I will test it on the weekend when I have time again.

**Comment by chempke** [comment]
Works perfect!

**Pull request closed without merging**
