### PR TITLE
Added Blackmailed.com, VogoV.com, UltraFilms.xxx | Bugfixs

### PR DESCRIPTION
**Pull request by kamuk90**
- Added blackmailed.com site to list (on linux tested)
for searching code use the sitemap.
for success finding the scene you need to enter at least one word contained in the name of the scene
> ex. Blackmailed-Secretary's Blackmailed Office Fuck its same like Blackmailed-Secretary's

- Added VogoV.com site to list  (on linux tested)
Actors and title searching available

- Added Ultrafilms.xxx site to list  (on linux tested)
Actors and title searching available

### CODE REVIEW

**Comment by claygoldfinch** [comment]
You gotta start looking at commit history. Your TeamSkeet bugfix breaks things I fixed a week ago (and fully explained in Issue #283). Additionally, why did you remove date match? 

```
            if searchDate:
                score = 100 - Util.LevenshteinDistance(searchDate, releaseDate)
            else:
                score = 100 - Util.LevenshteinDistance(searchTitle.lower(), titleNoFormatting.lower())
```

**Comment by claygoldfinch** [comment]
@kamuk90 Sorry, I don't mean to be mean. I appreciate your efforts in fixing stuff, but you gotta document your code. It makes it very hard to test if I don't understand why you did things.

**Comment by kamuk90** [comment]
No problem, I'll do my version and follow on my fork

**Comment by d2dyno** [comment]
That is an unfortunate attitude. Open source is all about everyone helping everyone. Hopefully, you will be back with some more documentation on your commits :)

**Pull request closed without merging**
