### PR TITLE
DDFNetwork fix

### LINKED ISSUE #302: Improve HouseofTaboo search
Currently, date is not supported, though date is listed on the search results page. In addition, many scenes will fail in the agent, such as `Houseoftaboo The Dark Room Dominator` for https://houseoftaboo.com/videos/the+dark+room+dominator/21974

### PR DESCRIPTION
**Pull request by DirtyRacer1337**
Fixes #302

Some scenes cannot be found on DDFNetwork site, so i think probably better replace the search link to the sub-site link. I also added search by date, but it's missing on some sub-site search results.

### CODE REVIEW

**Comment by claygoldfinch** [comment]
Thanks for doing this, was on my to-do list but hadn't gotten around to it yet.

Having some difficulties scraping actors on the scenes I've tested:
- DDFNetwork - Book us a Room Pronto (https://ddfnetwork.com/videos/book+us+a+room+pronto/18821)
- DDFNetwork - Lecherous Licking: Sexy College Redhead Hardcore Fucked (https://ddfnetwork.com/videos/lecherous+licking+sexy+college+redhead+hardcore+fucked/21279)

**Comment by claygoldfinch** [comment]
HairyTwatter doesn't seem to be working, either. May need to revert that back to using DDFNetwork search.

**Comment by DirtyRacer1337** [comment]
Found solution for scenes, what cannot be found on the main site, whey just has different names, I solved it with searching by id.
Hope now it's should work with every scene.

**Comment by claygoldfinch** [comment]
I'm gonna hold off on merging this because I think we're gonna have to end up changing it in a week. Looks like DDFNetwork and its sub-sites are being turned into something called "PornWorld".

https://ddfnetwork.com

**Pull request closed without merging**
