### PR TITLE
Update sitelist.md

### PR DESCRIPTION
**Pull request by drraymond27**

### CODE REVIEW

**Comment by DirtyRacer1337** [comment]
`PAsiteList.py` too

and no need to create PR for every commit

**Comment by drraymond27** [comment]
OK, I think that I change everything

**Comment by drraymond27** [comment]
> `PAsiteList.py` too
> 
> and no need to create PR for every commit

Something missing?

**Comment by DirtyRacer1337** [comment]
@drraymond27 next time don't create new branch for every change and create one pr

**Pull request merged**
