### PR TITLE
optimize CzechVR

### PR DESCRIPTION
**Pull request by ferengi82**
should no work on Linux.
and a small fix on actor search

### CODE REVIEW

**Comment by kamuk90** [comment]
> URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>

**Comment by kamuk90** [comment]
But this is working with this commit 
https://github.com/kamuk90/PhoenixAdult.bundle/commit/87b6a6740c0c7fb7c55853b8dfdff1ee32ec54c9

**Comment by ferengi82** [comment]
interresting, which os are you using?
on my ubunt linux it works fine.

i'll cange it later to your new version. thx.

**Comment by kamuk90** [comment]
> interresting, which os are you using?
> on my ubunt linux it works fine.
> 
> i'll cange it later to your new version. thx.

this is problem on Synology NAS

**Comment by kamuk90** [comment]
I added to my fork

**Pull request merged**
