### PR TITLE
XConfessions API support

### LINKED ISSUE #593: XConfessions matching
Attempting to match with XConfessions. Issue was addressed in 7/2019 but issue appears to persists.

site- XConfessions www.xconfessions.com
file- Misha Cross - The Couchsurfer.mp4
Search term- XConfessions Misha Cross The Couchsurfer

log attached

thanks
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4109890/com.plexapp.agents.phoenixadult.log)

### PR DESCRIPTION
**Pull request by DirtyRacer1337**
Testing required
Fixes #593

### CODE REVIEW

**Comment by fgage** [comment]
Thanks. Tested a few files. Matched one file but did not scrape actors or artwork. Attached a fresh log of attempts to match several files that came back with no result

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4111048/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Looks like search works only with title, try to rename your files to title only. And whats name of matched file

**Comment by fgage** [comment]
Here is the log that includes files that successfully matched by did not scrape actors or artwork.  

Files were "Carolina Abril Come Fly With Me" and "Amarna Miller an Appointment With My Master"
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4111104/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Are you sure you found scenes with that names, because even in site it doesn't work, as I said it's title only, the other problem fixed.

**Comment by fgage** [comment]
Yes and they matched again with all metadata this time. All issues seem resolved. I have included logs. thanks for your help. 

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4111221/com.plexapp.agents.phoenixadult.log)

**Comment by claygoldfinch** [comment]
```
2020-01-29 20:38:06,378 (337c) :  INFO (logkit:16) - *******MEDIA TITLE****** xconfessions - lesbian
2020-01-29 20:38:06,378 (337c) :  INFO (logkit:16) - Getting Search Settings for: xconfessions - lesbian
2020-01-29 20:38:06,378 (337c) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: xconfessions lesbian
2020-01-29 20:38:06,384 (337c) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: xconfessions lesbian
2020-01-29 20:38:06,385 (337c) :  INFO (logkit:16) - ^^^^^^^ siteID: 695
2020-01-29 20:38:06,385 (337c) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2020-01-29 20:38:06,385 (337c) :  INFO (logkit:16) - xconfessions vs xconfessions
2020-01-29 20:38:06,385 (337c) :  INFO (logkit:16) - 1
2020-01-29 20:38:06,387 (337c) :  INFO (logkit:16) - 7
2020-01-29 20:38:06,387 (337c) :  INFO (logkit:16) - searchTitle (before date processing): lesbian
2020-01-29 20:38:06,387 (337c) :  INFO (logkit:16) - Search Title: lesbian
2020-01-29 20:38:06,387 (337c) :  INFO (logkit:16) - lesbian
2020-01-29 20:38:06,868 (337c) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-01-29 20:38:06,868 (337c) :  DEBUG (runtime:924) - Response: [200] str, 2044 bytes
2020-01-29 20:38:08,275 (b00) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo1MDMzMXM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXM0OQpjb20ucGxleGFwcC5hZ2VudHMucGhvZW5peGFkdWx0Oi8vMTQ0fDY5NT9sYW5nPWVuczQKZ3VpZHM3CjE0NHw2OTVzMgppZHIwCg__
2020-01-29 20:38:08,276 (b00) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo1MDMzMXM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczUKTW92aWVzMTAKbWVkaWFfdHlwZXM0OQpjb20ucGxleGFwcC5hZ2VudHMucGhvZW5peGFkdWx0Oi8vMTQ0fDY5NT9sYW5nPWVuczQKZ3VpZHM3CjE0NHw2OTVzMgppZHIwCg__
2020-01-29 20:38:08,276 (b00) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.phoenixadult://144|695?lang=en
2020-01-29 20:38:08,279 (b00) :  DEBUG (model:234) - Deserializing from C:\Users\thisi\AppData\Local\Plex Media Server\Metadata\Movies\a\58717cf2f78121d1576a7997632c968a5be4166.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2020-01-29 20:38:08,280 (b00) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/50331/tree'
2020-01-29 20:38:08,288 (b00) :  INFO (logkit:16) - ******UPDATE CALLED*******
2020-01-29 20:38:08,289 (b00) :  INFO (logkit:16) - 695
2020-01-29 20:38:08,289 (b00) :  INFO (logkit:16) - ******UPDATE CALLED*******
2020-01-29 20:38:08,367 (b00) :  CRITICAL (core:574) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://144|695?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f5213a238\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1089, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 1778, in update
    metadata = PAsearchSites.siteXConfessions.update(metadata, siteID, movieGenres, movieActors)
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\siteXConfessions.py", line 51, in update
    data = bypassCloudflare(PAsearchSites.getSearchBaseURL(siteID))
  File "C:\Users\thisi\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\siteXConfessions.py", line 14, in bypassCloudflare
    data = urllib.urlopen(req).read()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 502: Bad Gateway

2020-01-29 20:38:08,368 (b00) :  DEBUG (model:229) - Serializing to C:\Users\thisi\AppData\Local\Plex Media Server\Metadata\Movies\a\58717cf2f78121d1576a7997632c968a5be4166.bundle\Contents\com.plexapp.agents.phoenixadult\Info.xml
2020-01-29 20:38:08,371 (b00) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2020-01-29 20:38:08,371 (b00) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Pull request merged**
