### PR TITLE
Update sitelist.md

### PR DESCRIPTION
**Pull request by yes12397**
with green tick ✅ are the sites which are working and tested with a sample file using different methods in enhanced search mode
green  tick ✅  with ⭕️red circle  its working but minor issue to have attention
with red cross ❌ are the sites which fail in search and has a problem
with Green cross ❎Progress to solve the  issue

Consider this as a status icon for each site and it will be easy to check whats next in queue to solve the issue
his is a sample of contribution i want to share in this group . so if its fine i can continue.

Note: any one welcome to contribute . am not familiar with github . so i leave it for the admins to decide where to locate and who to access

### CODE REVIEW

**Comment by claygoldfinch** [comment]
While I like this idea, I have a few thoughts:

1. It will be pretty difficult to confirm each site is working without running some sort of automated test every couple days (as proposed in Issue #34). Until we can have a system like that set up, I'd say it's better to assume that all sites are working, and only delineate the sites that are not.

2. I don't think minor site issues should be listed on the sitelist. Something like the Spizoo title issue (which should be opened as in issue in the Issue Tracker) is something a contributor could fix relatively quickly.

3. I think it's best to assume that all sites that are broken are currently being worked on. Some fixes take longer than others, and all contributors have different priorities/abilities/time available. For example:
  - TransAngels (again, please open an issue in the Issue Tracker, as I had no idea the site had changed) should be a relatively quick fix. I added the site myself and I'm familiar with the new site layout. Additionally, siteTransAngel.py only pulls code from TransAngels.com, so I don't have to worry about messing up other sites when I change the code.
  - FakeHub is going to be a harder fix. I am familiar with the new site layout, but FakeHub is integrated into networkSexyHub.py, which scrapes multiple sites. Most of these sites had similar layouts, but with FakeHub changing to a new layout it complicates things quite a bit. Additionally, I didn't write any of this code myself. I'll have to take a look at the design of each website to make sure I don't break anything with my fix.
  - Digital Playground required an entire rewrite, and a workaround for DVDs. I've had it up and running for scenes for quite a while, but the DVD workaround is kinda low priority as I don't have any Digital Playground DVDs myself.

Overall, I see this as a good way to let the average user know which sites are currently broken. However, I don't see it as a good way for contributors to track and fix site issues - the Issue Tracker allows for much more information and conversation.

**Comment by claygoldfinch** [comment]
@d2dyno, do you have any thoughts about altering/enhancing the sitelist?

**Comment by d2dyno** [comment]
I agree with @claygoldfinch we should assume all sites are working, unless noted otherwise. For long/outstanding issues with a site maybe we could create a 'known issues' section to put them in.

The main issue with this PR is how unpredictably sites will work or not, and how advanced fixes have to be. We're finding more and more sites using a new layout like Mofos/Babes, but don't know which plan to use it. Other sites have a simple 1 character html change that is easy to fix.

**Comment by yes12397** [comment]
Well said both of u . Will start to make an issue tickets  with logs for sites having issues. Do u want me to make a ticket for each or gather them in one ticket?

**Comment by d2dyno** [comment]
I think things will be easier to keep track of with each site/network's issues having their own ticket.

**Pull request closed without merging**
