### PR TITLE
MYLF search fix

### PR DESCRIPTION
**Pull request by DirtyRacer1337**
I added a search by ID, using a sitemap, it doesn't have all scenes and it's not updating every day, but it's better than nothing, in future it can fix problem #497

Now it should works without problem #497

### CODE REVIEW

**Comment by insickin** [comment]
Can you elaborate how I can search for a scene now i.e. with what combo must I search because I still can't find the scene's https://www.mylf.com/movies/2079/new-decade,-new-milf-pussy and https://www.mylf.com/movies/2093/got-mylf!

**Comment by DirtyRacer1337** [comment]
Are you sure, you are using my changes, because I can find that scenes, without problem?

**Comment by insickin** [comment]
Ok, I downloaded (again) the agent via your repository, restarted my Plex server tried a few search combos but it still does not work!

I've included a log for you:
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4108452/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
You did something wrong, I don't see my changes in the logs. Probably you forgot to change branch from `master` to `myfl`

**Comment by insickin** [comment]
Aha, that can be the thing! I assumed that by downloading the agent via the "normal" download link on your repository I'd get the fixes (didn't know that that was an option :stuck_out_tongue_winking_eye: ), I'm trying right now if it works whit the Myfl branch!

**Comment by DirtyRacer1337** [comment]
@insickin Enjoy!
@claygoldfinch What do yo think?

**Comment by insickin** [comment]
Is the Mylf sub site Mylfwood included in this update?

**Comment by DirtyRacer1337** [comment]
@insickin [Mylfwood](http://mylfwood.com/) redirected to the main site, and yes, you can find it

**Comment by insickin** [comment]
I'm asking because @d2dyno was asking for support in #1 for it.

**Comment by insickin** [comment]
I think that you can integrate this commit to the main branch, everything works for me! It is a shame that the MYLF site doesn't provide any form of date data (at least not that I can see/find)

**Pull request merged**
