### PR TITLE
DDFNetwork Fix

### LINKED ISSUE #302: Improve HouseofTaboo search
Currently, date is not supported, though date is listed on the search results page. In addition, many scenes will fail in the agent, such as `Houseoftaboo The Dark Room Dominator` for https://houseoftaboo.com/videos/the+dark+room+dominator/21974

### LINKED ISSUE #467: 1by-day Issue
All DDF Network scenes are matching well except 1By-Day. This is from the log and it's pretty clear what's happening. It seems to find the siteid and then include the 1byday minus the 1, meaning it is looking up byday and then the scene name. 

filename = "1byday - fingering for fun.mp4"

2019-11-06 11:17:38,063 (62c) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgowNTAzMDYyYTI3OGJjNGYzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczI0CjFieWRheSBGaW5nZXJpbmcgZm9yIEZ1bnM0Cm5hbWVzMTcxCkolM0ElNUNTZXJ2ZXJGb2xkZXJzJTVDQ29tcGFueSU1QzEwMCUyNSUyMEZMJTIwUmVhZHklNUMxQnktRGF5JTVDMWJ5LWRheSUyRTE4JTJFMDglMkUxNSUyRWFseXNzaWElMkVrZW50JTJFZmluZ2VyaW5nJTJFZm9yJTJFZnVuJTVDMWJ5ZGF5JTIwLSUyMGZpbmdlcmluZyUyMGZvciUyMGZ1biUyRW1wNHM4CmZpbGVuYW1lczQwCjA0M2JhM2I5OGNmNWI0MDNhMjYwZWVjYmNjZThmNjg4YTE1M2YwZmFzOApwbGV4SGFzaHM2CjYzMjk2NnM4CmR1cmF0aW9uczYKMzA5NDYxczIKaWRyMAo_
2019-11-06 11:17:38,063 (62c) :  DEBUG (runtime:49) - Received packed state data (7300 bytes)
2019-11-06 11:17:38,065 (62c) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgowNTAzMDYyYTI3OGJjNGYzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczI0CjFieWRheSBGaW5nZXJpbmcgZm9yIEZ1bnM0Cm5hbWVzMTcxCkolM0ElNUNTZXJ2ZXJGb2xkZXJzJTVDQ29tcGFueSU1QzEwMCUyNSUyMEZMJTIwUmVhZHklNUMxQnktRGF5JTVDMWJ5LWRheSUyRTE4JTJFMDglMkUxNSUyRWFseXNzaWElMkVrZW50JTJFZmluZ2VyaW5nJTJFZm9yJTJFZnVuJTVDMWJ5ZGF5JTIwLSUyMGZpbmdlcmluZyUyMGZvciUyMGZ1biUyRW1wNHM4CmZpbGVuYW1lczQwCjA0M2JhM2I5OGNmNWI0MDNhMjYwZWVjYmNjZThmNjg4YTE1M2YwZmFzOApwbGV4SGFzaHM2CjYzMjk2NnM4CmR1cmF0aW9uczYKMzA5NDYxczIKaWRyMAo_
2019-11-06 11:17:38,065 (62c) :  INFO (agentkit:957) - Searching for matches for {'openSubtitlesHash': '0503062a278bc4f3', 'name': '1byday Fingering for Fun', 'filename': 'J%3A%5CServerFolders%5CCompany%5C100%25%20FL%20Ready%5C1By-Day%5C1by-day%2E18%2E08%2E15%2Ealyssia%2Ekent%2Efingering%2Efor%2Efun%5C1byday%20-%20fingering%20for%20fun%2Emp4', 'plexHash': '043ba3b98cf5b403a260eecbcce8f688a153f0fa', 'duration': '632966', 'id': '309461'}
2019-11-06 11:17:38,065 (62c) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/309461/tree'
2019-11-06 11:17:38,069 (62c) :  INFO (logkit:16) - *******MEDIA TITLE****** 1byday Fingering for Fun
2019-11-06 11:17:38,069 (62c) :  INFO (logkit:16) - Getting Search Settings for: 1byday Fingering for Fun
2019-11-06 11:17:38,069 (62c) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation: 1byday Fingering for Fun
2019-11-06 11:17:38,073 (62c) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: 1byday Fingering for Fun
2019-11-06 11:17:38,076 (62c) :  INFO (logkit:16) - ^^^^^^^ siteID: 330
2019-11-06 11:17:38,076 (62c) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2019-11-06 11:17:38,076 (62c) :  INFO (logkit:16) -  vs 
2019-11-06 11:17:38,076 (62c) :  INFO (logkit:16) - 1
2019-11-06 11:17:38,076 (62c) :  INFO (logkit:16) - 7
2019-11-06 11:17:38,078 (62c) :  INFO (logkit:16) - searchTitle (before date processing): byday Fingering for Fun
2019-11-06 11:17:38,078 (62c) :  INFO (logkit:16) - Search Title: byday Fingering for Fun
2019-11-06 11:17:38,078 (62c) :  INFO (logkit:16) - byday%20Fingering%20for%20Fun
2019-11-06 11:17:38,081 (62c) :  DEBUG (runtime:88) - Sending packed state data (7332 bytes)
2019-11-06 11:17:38,081 (62c) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2019-11-06 11:17:42,937 (afc) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjMwOTQ2MXMyCmlkczI0CjFieWRheSBGaW5nZXJpbmcgZm9yIEZ1bnM0Cm5hbWVuczQKeWVhcnIwCg__
2019-11-06 11:17:42,938 (afc) :  DEBUG (runtime:49) - Received packed state data (7300 bytes)
2019-11-06 11:17:42,940 (afc) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjMwOTQ2MXMyCmlkczI0CjFieWRheSBGaW5nZXJpbmcgZm9yIEZ1bnM0Cm5hbWVuczQKeWVhcnIwCg__
2019-11-06 11:17:42,940 (afc) :  INFO (agentkit:957) - Searching for matches for {'year': None, 'id': '309461', 'name': '1byday Fingering for Fun'}
2019-11-06 11:17:42,940 (afc) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/309461/tree'
2019-11-06 11:17:42,946 (afc) :  INFO (logkit:16) - *******MEDIA TITLE****** 1byday Fingering for Fun
2019-11-06 11:17:42,946 (afc) :  INFO (logkit:16) - Getting Search Settings for: 1byday Fingering for Fun
2019-11-06 11:17:42,946 (afc) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation: 1byday Fingering for Fun
2019-11-06 11:17:42,950 (afc) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: 1byday Fingering for Fun
2019-11-06 11:17:42,953 (afc) :  INFO (logkit:16) - ^^^^^^^ siteID: 330
2019-11-06 11:17:42,953 (afc) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2019-11-06 11:17:42,953 (afc) :  INFO (logkit:16) -  vs 
2019-11-06 11:17:42,953 (afc) :  INFO (logkit:16) - 1
2019-11-06 11:17:42,953 (afc) :  INFO (logkit:16) - 7
2019-11-06 11:17:42,954 (afc) :  INFO (logkit:16) - searchTitle (before date processing): byday Fingering for Fun
2019-11-06 11:17:42,954 (afc) :  INFO (logkit:16) - Search Title: byday Fingering for Fun
2019-11-06 11:17:42,954 (afc) :  INFO (logkit:16) - byday%20Fingering%20for%20Fun
2019-11-06 11:17:42,957 (afc) :  DEBUG (runtime:88) - Sending packed state data (7332 bytes)
2019-11-06 11:17:42,957 (afc) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes

### PR DESCRIPTION
**Pull request by claygoldfinch**
Based off @DirtyRacer1337's code, just made a few changes. Unfortunately we'll probably have to update this in a few weeks, as www.DDFNetwork.com is now redirecting to www.pornworld.com...

Enhanced Search for DDFNetwork and all subsites with a search function. SceneID only for all subsites without a search function. 

Resolves #467, resolves #302.

### CODE REVIEW

**Comment by claygoldfinch** [comment]
Actually, I'm gonna close this out too. There's still a few sites that aren't working 100% and there's no point in putting more effort into this when any work done will have to be redone in a few weeks...

**Comment by claygoldfinch** [comment]
As sites with search functionality are working well with this code we might as well merge it in. Removed all sites without search functionality.

**Comment by DirtyRacer1337** [comment]
You made a mistake, in my PR #562 you can find that sites, if not by name, then by ID.
For example [Mona Kim Moment](http://sexvideocasting.com/videos/mona+kim+moment/19754), it can be found on DDF [Search page](https://ddfnetwork.com/videos/freeword/mona+kim+moment) and it have good cover with title.

**Comment by claygoldfinch** [comment]
Yeah, my dilemma here was:

1. Say "we support Hairy Twatter", but behind the scenes have search run through DDFNetwork.com. The issue with this is that scenes on Hairy Twatter may be differently named than on DDFNetwork.com (like you noticed). Or, they may not even be on DDFNetwork.com (quick example would be [The Blonde Muffin](http://hairytwatter.net/videos/the+blonde+muffin/19681)).
2. Say "we only support DDFNetwork, not Hairy Twatter" so that users know we only support what is on DDFNetwork.com. Technically, content from Hairy Twatter is on DDFNetwork.com. But this way you don't have any users asking why they can't find content.

I just didn't think it was worth the effort to:
1. Try to determine which subsites are fully supported via DDFNetwork.com.
2. Edit the agent so it works with each subsite via SceneID considering the fact that it's very likely DDFNetwork won't exist in it's current state in a few weeks.

That said, after some more though I'm re-adding the sites I removed, but changing the sitelist so hopefully it's a little more clear what's supported.

**Pull request merged**
