### PR TITLE
Allanalallthetime

### PR DESCRIPTION
**Pull request by ferengi82**
hi,

im trying to add https://www.allanalallthetime.com, no search, no siteid, nothing.
Only a List with most of the necessary Data.

The Search part is working, but im not sure how to get the metadata-update to work without a pageurl.

Maybe someone could look over it and give me a tipp how to continue.

### CODE REVIEW

**Comment by ferengi82** [comment]
i got it working, BUT its far from perfect.
if a new scene is added you have to remach all scenes .... (if you want to update the metadata)
maybe some of the pros can have a look

**Comment by jamesalexw** [comment]
Have a look at the code I made for PureCFNM network. It has no search it just uses the model name to land on the right page and then grabs the data to pass over to the metadata update. It might help you do what you need to get this working.

**Comment by ferengi82** [comment]
thanks for the advice, but on this site there is no link between model and scenes, every link go's to the join-form.

**Comment by jamesalexw** [comment]
Yeah, it was more that on PureCFNM the model page contained multiple scenes with no links, like the site you are trying to grab data from. Ignore that you don't have model pages, you have update pages. So the initial search code grabs the data after the user selects a scene from the returned list and then passes it over to the metadata section, if that makes sense.

**Comment by ferengi82** [comment]
not at the Moment, but i look in to it in a few days when i have more time, thanks

**Comment by DirtyRacer1337** [comment]
@ferengi82 If you not forget and still interested, site now have scene page `https://www.allanalallthetime.com/videos/31815/1594909475`, last part `/1594909475` not required, you can use `PAutils.getFromGoogleSearch()` to implement search and sceneID search

**Pull request closed without merging**
