### PR TITLE
GirlsWay Fix | Evil Angel Fix | LilHumpers Support | BellesaFilm…

### LINKED ISSUE #451: Evil Angel full DVD support
I see that we can tag scene's from Evil Angel but I can't get the agent to tag full DVD releases.

For example I'm trying to tag: "Evilangel - I Am Angela", non of the combo's given in #414 work, in the log I see that the agent searches via https://www.evilangel.com/en/video/ for full DVD releases their site uses  https://www.evilangel.com/en/movie/ so the difference is "/video/" "/movie/" 

[Log.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/3746980/Log.txt)

### LINKED ISSUE #486: Girlsway site makeover
The Girlsway site has had a makeover, so the agent can't find anything anymore! Can someone repair this site?

### PR DESCRIPTION
**Pull request by claygoldfinch**
GirlsWay
- Updated to SceneID only due to site changes. Resolves #486.
- Separated from NetworkGammaEnt.py.
- Added several subsites.

EvilAngel
- Updated to SceneID only (from DirectURL only). 
- DVDs now supported. Resolves #451.
- Separated from NetworkGammaEnt.py.

BellesaFilms
- Now supported. SceneID only.
@insickin

LilHumpers
- Now supported. SceneID only.
@insickin

TushyRaw
- Enhanced Search now supported.

ClubSeventeen (Find scenes here: https://www.clubseventeen.com/girls.php)
- Now supported. DirectURL only.
@MaLaCoiD

Elegant Angel
- Now supported. Limited search (Title/Cast). Only full DVDs supported.
@dismethis, @chempke, @chonka1, @insickin

FamilySinners
- Now supported. SceneID only.
@insickin

ReidMyLips
- Preliminary support. DirectURL only.
@dismethis, @insickin

PlayboyPlus
- Now supported. Limited Search.
@insickin

MeanaWolf
- Now supported. Limited Search.
@mcneleon

Other
- Removed version number.
- Fixed minor punctuation issue in init.py.
- Minor changes to Babes.py.
- Added separate template file for SceneID.
- Sitelist updates.
- Genre merges.
- Code cleanup.

### CODE REVIEW

**Comment by insickin** [comment]
I can confirm that the Girlsway site works, only 1 broken thing; the agent doesn't scrape the actor info, if this can be fixed?

**Comment by claygoldfinch** [comment]
Have some examples of scenes that aren't working?

**Comment by insickin** [comment]
For:

Girlsway:
All scenes are affected, I tested with their latest released scene's like for example: https://www.girlsway.com/en/video/girlsway/showcase%3A-jade-baker/166509

Evil Angel:
All the DVD releases loose scene's load the description fine, for example https://www.evilangel.com/en/movie/I-Am-Angela/70357 loads everything except the description

**Comment by claygoldfinch** [comment]
@insickin changes made, feel free to re-test.

**Comment by HWatBobby** [comment]
I noticed in PASearachSites 18OnlyGirls and GirlCore have the same site ID [794]. I assume GirlCore through to Elegant Angel will need to be changed +1 as well in the relevant files.

**Comment by claygoldfinch** [comment]
> 
> 
> I noticed in PASearachSites 18OnlyGirls and GirlCore have the same site ID [794]. I assume GirlCore through to Elegant Angel will need to be changed +1 as well in the relevant files.

Thanks for the catch! Resolved.

**Comment by chempke** [comment]
Wow thats a huge update! i really appreciate that =) 
Any plans to add direct URL support for Elegant Angel for idividuall scenes? 

Unfortunately, I have little time at the moment to test the update, but I will do it in the next few days.
Good work!

**Comment by insickin** [comment]
> 
> 
> @insickin changes made, feel free to re-test.

Thanks, Girlsway an Evil Angel tag perfectly now!

**Comment by claygoldfinch** [comment]
Thanks for all the feedback, everyone! Hopefully, I will have the time for some more big updates like this in the near future. And yes, the plan is to have Direct URL up and running for individual ElegantAngel scenes soon!

@insickin thanks for testing it out! I'll take a look at those scenes.

**Comment by insickin** [comment]
The agent can't find:

https://www.elegantangel.com/shop/1657385/intimate-passions-porn-videos.html
and
https://www.elegantangel.com/shop/1649309/intimate-passions-vol-2-porn-movies.html

**Comment by pedrolara-boop** [comment]
Girlsway is working!
Maybe also take the opportunity to remove Girlfriendfilms from the NetworkGammaEnt.py.
It hasn't worked for since august, and will make it easier for someone to try to write a fix. #347

**Comment by insickin** [comment]
Another DVD release that the agent can't find:

https://www.elegantangel.com/1049653/real-female-orgasms-5-porn-videos.html

Of that series the agent only finds part 2 and 4 the rest of them (1 to 16) cant be found via the agent

**Comment by pedrolara-boop** [comment]
@insickin have you test to search the same terms on the website? 
The search terms might be useful to find out why it does not show.

for "elegantangel - orgasms 5"
This is the search results that show on plex:
https://www.elegantangel.com/streaming-elegant-angel-dvds-on-video.html?fq=orgasms%205

The only way I could find was using the website, and it searches differently than the plug-in.
https://www.elegantangel.com/Search?q=real%20orgasms%205

Maybe the plug-in uses the other address to find the DVDs also? @claygoldfinch

**Comment by insickin** [comment]
I type (or copy) "real female orgasms 5" in the search bar and below that the "link"/found movies appears for "real female orgasms 5"

**Comment by pedrolara-boop** [comment]
Something kind of cool happened. You can now use the scene ID from adulttime.com on girlsway to fetch from other adulttime non-supported sites. 
Adulttime is their kind of new hub website that gives you access to Girlsway, Vivid, Fantasy Massage, Pure Taboo, Burning Angel, 21 Sextury, Devil'sFilm and Rocco Siffredi. Some videos from vivid and DevilsFilm are not even available on their own website. 
Girlsway uses the same website structure as adulttime, unfortunately, you cannot perform searches, unless you are a member.

Here is an example
https://www.girlsway.com/en/video/1/1/149511
Girlsway - 149511

It only gets the studio wrong, but the right one shows after a /. Maybe could be added support like that.

**Comment by pedrolara-boop** [comment]
Hm, it fails to get the actors' name if there is no summary.
https://www.girlsway.com/en/video/1/1/142629
Girlsway - 142629

**Comment by claygoldfinch** [comment]
Updated Elegant Angel search URL to https://www.elegantangel.com/Search?fq=, as it looks like all releases are available there. Still a few bugs to be ironed out, some scenes aren't pulling actors, images, etc. Lemme know if you run into issues with any scenes in particular.

Submitted a bugfix to deal with the GirlsWay scene that was erroring out, as well.

Thanks for all the help!

**Comment by insickin** [comment]
> 
> 
> Something kind of cool happened. You can now use the scene ID from adulttime.com on girlsway to fetch from other adulttime non-supported sites.
> Adulttime is their kind of new hub website that gives you access to Girlsway, Vivid, Fantasy Massage, Pure Taboo, Burning Angel, 21 Sextury, Devil'sFilm and Rocco Siffredi. Some videos from vivid and DevilsFilm are not even available on their own website.
> Girlsway uses the same website structure as adulttime, unfortunately, you cannot perform searches, unless you are a member.
> 
> Here is an example
> https://www.girlsway.com/en/video/1/1/149511
> Girlsway - 149511
> 
> It only gets the studio wrong, but the right one shows after a /. Maybe could be added support like that.

That's great news, if this can be implemented!

> Updated Elegant Angel search URL to https://www.elegantangel.com/Search?fq=, as it looks like all releases are available there. Still a few bugs to be ironed out, some scenes aren't pulling actors, images, etc. Lemme know if you run into issues with any scenes in particular.

Submitted a bugfix to deal with the GirlsWay scene that was erroring out, as well.

Thanks for all the help!

I will test my non working Elegant Angel scene's/DVD's 

> @insickin Family Sinners now supported, as well.

So many thanks man, you're the man!

**Comment by diegogallina** [comment]
@claygoldfinch This has tested GREAT with GirlsWay scenes since, thanks so much!

**Comment by HWatBobby** [comment]
RE: Strike3 Network Fixes

After implementing the changes made to PASearchSites for Strike3 network sites (Vixen, Tushy, etc) when I search using the file name "Vixen 2019 12 10 Let Me In" I get no search results, but if I leave the date out , "Vixen Let Me In", I get results. Would it be possible to get it so it ignores the date in the file name like it used to?

**Comment by claygoldfinch** [comment]
@HWatBobby Updated, try now.

**Comment by cactuzjak** [comment]
having an issue where no matter what i match on any site the only genres that get tagged is "Doggystyle (Position)"

**Comment by claygoldfinch** [comment]
@cactuzjak Thanks for the heads up, my latest commit should resolve that. If you're still running into issues, try rebooting Plex.

**Comment by claygoldfinch** [comment]
Going to merge this in. Feel free to open issues in the issue tracker from this point forward.

**Pull request merged**
